# Auto-generated from chat/vocabulary.py

LANGUAGE_DATA = {'display_name': 'Néerlandais',
 'categories': [{'name': 'Alimentation',
                 'words': [{'original': 'Quoi?', 'translation': 'wat'},
                           {'original': 'rien', 'translation': 'niets'},
                           {'original': 'quelques chose', 'translation': 'iets'},
                           {'original': 'tout', 'translation': 'hele'},
                           {'original': 'chaque', 'translation': 'elke'},
                           {'original': 'fruit', 'translation': 'vrucht'},
                           {'original': 'légumes', 'translation': 'groente'},
                           {'original': 'fromage', 'translation': 'kaas'},
                           {'original': 'pain', 'translation': 'brood'},
                           {'original': 'poisson', 'translation': 'vis'},
                           {'original': 'animal', 'translation': 'dier'},
                           {'original': 'viande', 'translation': 'vlees'},
                           {'original': 'sucre', 'translation': 'suiker'},
                           {'original': 'sel', 'translation': 'zout'},
                           {'original': 'poivre', 'translation': 'peper'},
                           {'original': 'verre', 'translation': 'glas'},
                           {'original': 'café', 'translation': 'koffie'},
                           {'original': 'thé', 'translation': 'thee'},
                           {'original': 'eau', 'translation': 'water'},
                           {'original': 'lait', 'translation': 'melk'},
                           {'original': 'huile', 'translation': 'olie'},
                           {'original': 'bière', 'translation': 'bier'},
                           {'original': 'vin', 'translation': 'wijn'},
                           {'original': 'travail', 'translation': 'werk'},
                           {'original': 'argent', 'translation': 'geld'},
                           {'original': 'livre', 'translation': 'het boek'},
                           {'original': 'vetement', 'translation': 'kleding'},
                           {'original': 'autre', 'translation': 'ander'},
                           {'original': 'difference', 'translation': 'verschil'},
                           {'original': 'ainsi', 'translation': 'zo'},
                           {'original': 'comme', 'translation': 'zoals'},
                           {'original': 'aussi', 'translation': 'ook'},
                           {'original': 'pour (moi)', 'translation': 'voor (mij)'},
                           {'original': 'avec (moi)', 'translation': 'met (mij)'},
                           {'original': 'sans (moi)', 'translation': 'zonder (mij)'},
                           {'original': 'ensemble', 'translation': 'samen'},
                           {'original': 'seul', 'translation': 'alleen'}]},
                {'name': 'Expressions & Pensée',
                 'words': [{'original': 'il y a', 'translation': 'er is'},
                           {'original': "y a t'il?", 'translation': 'is er?'},
                           {'original': "c'est", 'translation': 'het is'},
                           {'original': 'ne pas', 'translation': 'niet'},
                           {'original': 'pas de', 'translation': 'geen'},
                           {'original': "j'aime", 'translation': 'ik houd van'},
                           {'original': 'je veux', 'translation': 'ik wil'},
                           {'original': 'je voudrai', 'translation': 'ik wou graag'},
                           {'original': "j'ai envie", 'translation': 'ik heb zin'},
                           {'original': 'voulez vous', 'translation': 'wilt u'},
                           {'original': 'il faut', 'translation': 'het is nodig'},
                           {'original': "c'est pas la peine", 'translation': 'het is niet nodig'},
                           {'original': 'je dois', 'translation': 'ik moet'},
                           {'original': 'vous devez', 'translation': 'jullie moeten'},
                           {'original': "j'ai besoin", 'translation': 'ik heb .. nodig'},
                           {'original': 'je sais', 'translation': 'ik weet'},
                           {'original': 'savez vous', 'translation': 'weet u'},
                           {'original': 'je connais', 'translation': 'ik ken'},
                           {'original': 'connaissez vous', 'translation': 'kent u'},
                           {'original': 'je peux', 'translation': 'ik kan'},
                           {'original': 'pouvez vous', 'translation': 'kan u'},
                           {'original': 'je pense que', 'translation': 'ik denk dat'},
                           {'original': 'je crois', 'translation': 'ik geloof'},
                           {'original': 'pour', 'translation': 'voor'},
                           {'original': 'aimer', 'translation': 'houden van'},
                           {'original': 'pouvoir', 'translation': 'kunnen'},
                           {'original': 'peut-être', 'translation': 'misschien'},
                           {'original': 'probablement', 'translation': 'waarschijnlijk'},
                           {'original': 'possible', 'translation': 'mogelijk'},
                           {'original': 'pas possible', 'translation': 'onmogelijk'},
                           {'original': 'couleur', 'translation': 'kleur'},
                           {'original': 'rouge', 'translation': 'rod'},
                           {'original': 'bleu', 'translation': 'blauw'},
                           {'original': 'blanc', 'translation': 'witt'},
                           {'original': 'jaune', 'translation': 'geel'},
                           {'original': 'vert', 'translation': 'groen'},
                           {'original': 'noir', 'translation': 'zwart'}]},
                {'name': "Verbes d'action",
                 'words': [{'original': 'faire', 'translation': 'doen/maken'},
                           {'original': 'penser', 'translation': 'denken'},
                           {'original': 'travailler', 'translation': 'werken'},
                           {'original': 'chercher', 'translation': 'opzoeken'},
                           {'original': 'trouver', 'translation': 'vinden'},
                           {'original': 'marcher', 'translation': 'lopen'},
                           {'original': 'se promener', 'translation': 'wandelen'},
                           {'original': 'aller', 'translation': 'gaan'},
                           {'original': 'venir', 'translation': 'komen'},
                           {'original': 'partir', 'translation': 'weggaan'},
                           {'original': 'attendre', 'translation': 'wachten'},
                           {'original': 'écrire', 'translation': 'schrijven'},
                           {'original': 'lire', 'translation': 'lezen'},
                           {'original': 'commencer', 'translation': 'beginnen'},
                           {'original': 'finir', 'translation': 'afmaken'},
                           {'original': 'rester', 'translation': 'blijven'},
                           {'original': 'entrer', 'translation': 'binnengaan'},
                           {'original': 'tourner', 'translation': 'afslaan'},
                           {'original': "s'asseoir", 'translation': 'zitten'},
                           {'original': 'sortir', 'translation': 'buitengaan'},
                           {'original': 'courir', 'translation': 'rennen'},
                           {'original': 'regarder', 'translation': 'kijken'},
                           {'original': 'voir', 'translation': 'zien'},
                           {'original': 'entendre', 'translation': 'horen'},
                           {'original': 'boire', 'translation': 'drinken'},
                           {'original': 'prendre', 'translation': 'nemen'},
                           {'original': 'acheter', 'translation': 'kopen'},
                           {'original': 'manger', 'translation': 'eten'},
                           {'original': 'tenir', 'translation': 'houden'},
                           {'original': 'dormir', 'translation': 'slapen'},
                           {'original': 'donner', 'translation': 'geven'},
                           {'original': 'payer', 'translation': 'betalen'},
                           {'original': 'parler', 'translation': 'spreken'},
                           {'original': 'dire', 'translation': 'zeggen'},
                           {'original': 'demander', 'translation': 'vragen'},
                           {'original': 'apprendre', 'translation': 'leren'},
                           {'original': 'comprendre', 'translation': 'begrijpen'},
                           {'original': 'habiter', 'translation': 'wonen'}]},
                {'name': 'Pronoms & Lieux',
                 'words': [{'original': 'Qui?', 'translation': 'wie'},
                           {'original': 'personne', 'translation': 'niemand'},
                           {'original': "quelqu'un", 'translation': 'iemand'},
                           {'original': 'tout le monde', 'translation': 'iedereen'},
                           {'original': 'enfant', 'translation': 'kinder'},
                           {'original': 'fils', 'translation': 'zoon'},
                           {'original': 'fille', 'translation': 'dochter'},
                           {'original': 'mère', 'translation': 'moeder'},
                           {'original': 'père', 'translation': 'vader'},
                           {'original': 'frère', 'translation': 'broer'},
                           {'original': 'soeur', 'translation': 'zuster'},
                           {'original': 'ami(e)', 'translation': 'vriend'},
                           {'original': 'ma femme', 'translation': 'mijn vrouw'},
                           {'original': 'mon', 'translation': 'mijn'},
                           {'original': 'ton', 'translation': 'je'},
                           {'original': 'son', 'translation': 'zijn,haar'},
                           {'original': 'notre', 'translation': 'onze'},
                           {'original': 'votre', 'translation': 'uw'},
                           {'original': 'leurs', 'translation': 'hun'},
                           {'original': 'je suis', 'translation': 'ik ben'},
                           {'original': 'tu es', 'translation': 'je bent'},
                           {'original': 'il,elle est', 'translation': 'hij,ze is'},
                           {'original': 'nous sommes', 'translation': 'we zijn'},
                           {'original': 'vous êtes', 'translation': 'u bent'},
                           {'original': 'ils sont', 'translation': 'zij zijn'},
                           {'original': "j'ai", 'translation': 'ik heb'},
                           {'original': 'tu as', 'translation': 'je hebt'},
                           {'original': 'il, elle a', 'translation': 'hij,ze heeft'},
                           {'original': 'nous avons', 'translation': 'we hebben'},
                           {'original': 'vous avez', 'translation': 'u heeft'},
                           {'original': 'ils ont', 'translation': 'zij hebben'},
                           {'original': 'de', 'translation': 'van'},
                           {'original': 'ceci', 'translation': 'deze/dit'},
                           {'original': 'cela', 'translation': 'die/dat'},
                           {'original': 'oui (volontier)', 'translation': 'ja (graag)'},
                           {'original': 'non', 'translation': 'nee'},
                           {'original': "d'accord", 'translation': 'akkoord'}]},
                {'name': 'Maison & Ville',
                 'words': [{'original': 'Où?', 'translation': 'waar'},
                           {'original': 'nulle-part', 'translation': 'norgens'},
                           {'original': 'quelques part', 'translation': 'ergens'},
                           {'original': 'partout', 'translation': 'overal'},
                           {'original': 'ici', 'translation': 'hier'},
                           {'original': 'là-bas', 'translation': 'daar'},
                           {'original': 'dessous', 'translation': 'onder'},
                           {'original': 'devant', 'translation': 'vôôr'},
                           {'original': 'à gauche', 'translation': 'links'},
                           {'original': 'vers', 'translation': 'naar'},
                           {'original': 'derrière', 'translation': 'achter'},
                           {'original': 'à côté', 'translation': 'naast'},
                           {'original': 'à droite', 'translation': 'rechts'},
                           {'original': 'tout droit', 'translation': 'rechtdoor'},
                           {'original': 'dans', 'translation': 'in'},
                           {'original': 'en haut', 'translation': 'boven'},
                           {'original': 'dessus', 'translation': 'boven'},
                           {'original': "à l'intérieur", 'translation': 'binnen'},
                           {'original': "à l'exterieur", 'translation': 'buiten'},
                           {'original': 'maison', 'translation': 'huis'},
                           {'original': 'cuisine', 'translation': 'koeken'},
                           {'original': 'table', 'translation': 'tafel'},
                           {'original': 'chaise', 'translation': 'stoel'},
                           {'original': 'soleil', 'translation': 'zon'},
                           {'original': 'montagnes', 'translation': 'bergen'},
                           {'original': 'mer', 'translation': 'zee'},
                           {'original': 'ville', 'translation': 'stad'},
                           {'original': 'rue', 'translation': 'straat/weg'},
                           {'original': 'magasin', 'translation': 'winkel'},
                           {'original': 'chambre', 'translation': 'kamer'},
                           {'original': 'lit', 'translation': 'bed'},
                           {'original': 'salle de bain', 'translation': 'badkamer'},
                           {'original': 'avion', 'translation': 'vligetuig'},
                           {'original': 'voiture', 'translation': 'wagen'},
                           {'original': 'bus', 'translation': 'bus'},
                           {'original': 'train', 'translation': 'trein'},
                           {'original': 'voyage', 'translation': 'reis'}]},
                {'name': 'Temps',
                 'words': [{'original': 'Quand?', 'translation': 'wanneer'},
                           {'original': 'temps', 'translation': 'tijd'},
                           {'original': 'jamais', 'translation': 'nooit'},
                           {'original': 'parfois', 'translation': 'af en toe / soms'},
                           {'original': 'souvent', 'translation': 'dikwijls'},
                           {'original': 'toujours', 'translation': 'altijd/steeds'},
                           {'original': 'année', 'translation': 'jaar'},
                           {'original': 'mois', 'translation': 'maand'},
                           {'original': 'semaine', 'translation': 'week'},
                           {'original': 'jour', 'translation': 'dag'},
                           {'original': '(à) .. heure', 'translation': '(om) .. uur'},
                           {'original': 'minutes', 'translation': 'minuten'},
                           {'original': 'seconde', 'translation': 'seconde'},
                           {'original': 'avant', 'translation': 'voor'},
                           {'original': 'maintenant', 'translation': 'nu'},
                           {'original': 'après', 'translation': 'na'},
                           {'original': 'tout de suite', 'translation': 'onmiddelijk / dadelik'},
                           {'original': 'matin', 'translation': 'morgen'},
                           {'original': 'après-midi', 'translation': 'middag'},
                           {'original': 'soir', 'translation': 'avond'},
                           {'original': 'nuit', 'translation': 'nacht'},
                           {'original': 'hier', 'translation': 'gisteren'},
                           {'original': "aujourd'hui", 'translation': 'vandaag'},
                           {'original': 'demain', 'translation': 'morgen'},
                           {'original': 'tôt', 'translation': 'vroeg'},
                           {'original': 'bientôt', 'translation': 'binnenkort'},
                           {'original': 'prochain', 'translation': 'volgende'},
                           {'original': 'tard', 'translation': 'laat'},
                           {'original': 'dernier', 'translation': 'vorige'},
                           {'original': 'déjà', 'translation': 'al'},
                           {'original': 'depuis', 'translation': 'sinds'},
                           {'original': 'encore', 'translation': 'nog'},
                           {'original': "jusqu'à", 'translation': 'tot'},
                           {'original': 'de nouveau', 'translation': 'weer'},
                           {'original': 'toujours pas', 'translation': 'steeds niet'}]},
                {'name': 'Adjectifs',
                 'words': [{'original': 'Comment?', 'translation': 'hoe'},
                           {'original': 'grand', 'translation': 'grot'},
                           {'original': 'petit', 'translation': 'klein'},
                           {'original': 'haut', 'translation': 'hoog'},
                           {'original': 'bas', 'translation': 'lag'},
                           {'original': 'beau', 'translation': 'mooi'},
                           {'original': 'vide', 'translation': 'leeg'},
                           {'original': 'plein', 'translation': 'vol'},
                           {'original': 'ouvert', 'translation': 'open'},
                           {'original': 'fermé', 'translation': 'gesloten'},
                           {'original': 'près', 'translation': 'dichtbij'},
                           {'original': 'loin', 'translation': 'ver'},
                           {'original': 'chaud', 'translation': 'warm'},
                           {'original': 'froid', 'translation': 'koud'},
                           {'original': 'nouveau', 'translation': 'nieuw'},
                           {'original': 'ancien', 'translation': 'oud'},
                           {'original': 'jeune', 'translation': 'jong'},
                           {'original': 'fatigué', 'translation': 'moe'},
                           {'original': 'malade', 'translation': 'ziek'},
                           {'original': 'prêt', 'translation': 'klaar'},
                           {'original': 'propre', 'translation': 'schoon'},
                           {'original': 'sale', 'translation': 'vuil'},
                           {'original': 'lourd', 'translation': 'zwaar'},
                           {'original': 'bon', 'translation': 'lekkere'},
                           {'original': 'bien', 'translation': 'goed'},
                           {'original': 'mauvais', 'translation': 'slecht'},
                           {'original': 'gentil', 'translation': 'aardig'},
                           {'original': 'content', 'translation': 'blij'},
                           {'original': 'difficile', 'translation': 'moeilijk'},
                           {'original': 'facile', 'translation': 'gemakkelijk'},
                           {'original': 'intéressant', 'translation': 'interessant'},
                           {'original': "(j'ai) faim", 'translation': '(ik heb) honger'},
                           {'original': 'rapide', 'translation': 'vlug'},
                           {'original': 'lent', 'translation': 'langzaam'},
                           {'original': 'cher', 'translation': 'duur'},
                           {'original': 'important', 'translation': 'belangrijk'},
                           {'original': 'célèbre', 'translation': 'beroemd/bekende'},
                           {'original': 'interdit', 'translation': 'verboden'}]},
                {'name': 'Chiffres & Quantité',
                 'words': [{'original': 'Combien?', 'translation': 'hoeveel'},
                           {'original': 'un peu', 'translation': 'een beetje / wat'},
                           {'original': 'peu', 'translation': 'weinig'},
                           {'original': 'beaucoup', 'translation': 'veel / talrijke'},
                           {'original': 'très', 'translation': 'heel'},
                           {'original': 'moins', 'translation': 'minder'},
                           {'original': 'plus', 'translation': 'meer'},
                           {'original': 'presque', 'translation': 'bijna'},
                           {'original': 'environ', 'translation': 'ongeveer'},
                           {'original': 'trop', 'translation': 'te veel'},
                           {'original': 'assez', 'translation': 'genoeg/nogal'},
                           {'original': '1', 'translation': 'een'},
                           {'original': '2', 'translation': 'twee'},
                           {'original': '3', 'translation': 'drie'},
                           {'original': '4', 'translation': 'vier'},
                           {'original': '5', 'translation': 'vijf'},
                           {'original': '6', 'translation': 'zes'},
                           {'original': '7', 'translation': 'zeven'},
                           {'original': '8', 'translation': 'acht'},
                           {'original': '9', 'translation': 'negen'},
                           {'original': '10', 'translation': 'tien'},
                           {'original': '11', 'translation': 'elf'},
                           {'original': '12', 'translation': 'twaalf'},
                           {'original': '13', 'translation': 'dertien'},
                           {'original': '20', 'translation': 'twintig'},
                           {'original': '30', 'translation': 'dertig'},
                           {'original': '100', 'translation': 'honderd'},
                           {'original': '1000', 'translation': 'duizend'},
                           {'original': 'mais', 'translation': 'maar'},
                           {'original': 'ou', 'translation': 'of'},
                           {'original': 'et', 'translation': 'en'},
                           {'original': 'donc', 'translation': 'dus'},
                           {'original': 'alors', 'translation': 'dan'},
                           {'original': 'Pourquoi?', 'translation': 'waarom'},
                           {'original': 'parce que', 'translation': 'want/omdat'},
                           {'original': 'par example', 'translation': 'zoals'},
                           {'original': 'Quel(le,s)?', 'translation': 'welke'}]},
                {'name': 'Politesse',
                 'words': [{'original': 'bonjour', 'translation': 'goedendag'},
                           {'original': 'salut', 'translation': 'hallo'},
                           {'original': 'comment vas tu', 'translation': 'hoe gaat het (met u)?'},
                           {'original': 'je vais bien', 'translation': 'het gaat goed met me'},
                           {'original': 'quoi de neuf', 'translation': 'wat is nieuw?'},
                           {'original': 'bonne journée', 'translation': 'goede dag'},
                           {'original': 'bonsoir', 'translation': 'goedenavond'},
                           {'original': 'bonne nuit', 'translation': 'goedenacht'},
                           {'original': 'aurevoir', 'translation': 'tot ziens'},
                           {'original': 'bienvenu', 'translation': 'welkom'},
                           {'original': "s'il vous plaît", 'translation': 'alstublieft'},
                           {'original': 'merci (beaucoup)', 'translation': 'dank u (wel)/ bedankt'},
                           {'original': 'de rien', 'translation': 'graag gedaan'},
                           {'original': 'excusez moi', 'translation': 'excuseert u me'},
                           {'original': 'désolé', 'translation': 'het spijt me'},
                           {'original': "c'est pas grave", 'translation': 'het is niet erg'},
                           {'original': 'félicitations', 'translation': 'gefeliciteerd'},
                           {'original': 'comment vous appelez vous?', 'translation': 'hoe het u'},
                           {'original': "je m'appele", 'translation': 'ik heet'},
                           {'original': 'enchanté', 'translation': 'ik ben blij u te leren kennen'},
                           {'original': 'voici', 'translation': 'hier is'},
                           {'original': 'bon appétit', 'translation': 'eet smakelijk'},
                           {'original': "c'était très bon",
                            'translation': 'het was heel smakelijk'},
                           {'original': "l'addition", 'translation': 'de rekening'},
                           {'original': 'santé!', 'translation': 'proost'},
                           {'original': "je n'ai pas compris", 'translation': 'ik begreep niet'},
                           {'original': 'je ne sais pas', 'translation': 'ik weet niet'},
                           {'original': 'attention', 'translation': 'kijk uit'}]}]}
