# Auto-generated from chat/vocabulary.py

LANGUAGE_DATA = {'display_name': 'Allemand',
 'categories': [{'name': 'Alimentation',
                 'words': [{'original': 'nourriture', 'translation': 'die Nahrung'},
                           {'original': 'rien', 'translation': 'nichts'},
                           {'original': 'quelque chose', 'translation': 'etwas'},
                           {'original': 'tout', 'translation': 'alles'},
                           {'original': 'pain', 'translation': 'das Brod'},
                           {'original': 'sel', 'translation': 'Salz'},
                           {'original': 'poivre', 'translation': 'Pfeffer'},
                           {'original': 'sucre', 'translation': 'Zucker'},
                           {'original': 'plante', 'translation': 'Pflanze'},
                           {'original': 'animal', 'translation': 'Tier'},
                           {'original': 'viande', 'translation': 'das Fleisch'},
                           {'original': 'poisson', 'translation': 'Fisch'},
                           {'original': 'fromage', 'translation': 'der Käse'},
                           {'original': 'verre', 'translation': 'das Glas'},
                           {'original': 'café', 'translation': 'der Kaffee'},
                           {'original': 'thé', 'translation': 'der Tee'},
                           {'original': 'eau', 'translation': 'das Wasser'},
                           {'original': 'lait', 'translation': 'die Milch'},
                           {'original': 'huile', 'translation': 'öl'},
                           {'original': 'bière', 'translation': 'das Bier'},
                           {'original': 'vin', 'translation': 'Wein'},
                           {'original': 'travail', 'translation': 'die Arbeit'},
                           {'original': 'argent', 'translation': 'das Geld'},
                           {'original': 'livre', 'translation': 'Buch'},
                           {'original': 'v^etement', 'translation': 'Kleidung'},
                           {'original': 'oui', 'translation': 'ja'},
                           {'original': 'non', 'translation': 'nein'},
                           {'original': 'si', 'translation': 'doch'},
                           {'original': "d'accord", 'translation': 'okay'},
                           {'original': 'tête', 'translation': 'der Kopf'},
                           {'original': 'cheveux', 'translation': 'die Haare'},
                           {'original': 'oeil', 'translation': 'das Auge'},
                           {'original': 'oreille', 'translation': 'das Ohr'},
                           {'original': 'nez', 'translation': 'die Nase'},
                           {'original': 'bouche', 'translation': 'der Mund'},
                           {'original': 'dent', 'translation': 'der Zahn'},
                           {'original': 'main', 'translation': 'die Hand'},
                           {'original': 'pied', 'translation': 'der Fuss'}]},
                {'name': 'Expressions & Pensée',
                 'words': [{'original': 'ne pas', 'translation': 'nicht'},
                           {'original': 'pas de', 'translation': 'kein'},
                           {'original': 'il y a', 'translation': 'es gibt'},
                           {'original': "y a t'il?", 'translation': 'gibt es'},
                           {'original': "j'aime", 'translation': 'ich mag'},
                           {'original': "j'aimerai", 'translation': 'ich möchte'},
                           {'original': 'aimeriez vous', 'translation': 'möchten Sie'},
                           {'original': 'voulez vous', 'translation': 'wollen Sie'},
                           {'original': 'je dois', 'translation': 'ich muss'},
                           {'original': "c'est pas la peine", 'translation': 'es ist nicht nötig'},
                           {'original': 'vous devez', 'translation': 'Sie müssen'},
                           {'original': 'je sais', 'translation': 'ich weiss'},
                           {'original': 'savez vous', 'translation': 'wissen Sie'},
                           {'original': 'je (te) connais', 'translation': 'ich kenne (dich)'},
                           {'original': 'connaissez vous', 'translation': 'kennen Sie'},
                           {'original': 'je peux', 'translation': 'ich kann/darf'},
                           {'original': 'vous pouvez', 'translation': 'Sie können/dürfen'},
                           {'original': 'je pense', 'translation': 'ich denke'},
                           {'original': 'je crois', 'translation': 'ich glaube'},
                           {'original': 'pour', 'translation': 'fur'},
                           {'original': 'aimer', 'translation': 'mogen'},
                           {'original': 'pouvoir', 'translation': 'konnen'},
                           {'original': 'peut-être', 'translation': 'vielleicht'},
                           {'original': 'pas possible', 'translation': 'unmöglich'}]},
                {'name': "Verbes d'action",
                 'words': [{'original': 'faire', 'translation': 'machen'},
                           {'original': 'penser', 'translation': 'denken'},
                           {'original': 'chercher', 'translation': 'holen'},
                           {'original': 'trouver', 'translation': 'finden'},
                           {'original': 'attendre', 'translation': 'warten'},
                           {'original': 'commencer', 'translation': 'anfangen'},
                           {'original': 'écrire', 'translation': 'schreiben'},
                           {'original': 'lire', 'translation': 'lesen'},
                           {'original': 'travailler', 'translation': 'arbeiten'},
                           {'original': 'apprendre', 'translation': 'lernen'},
                           {'original': 'comprendre', 'translation': 'verstehen'},
                           {'original': 'regarder', 'translation': 'ansehen'},
                           {'original': 'voir', 'translation': 'sehen'},
                           {'original': 'prendre', 'translation': 'nehmen'},
                           {'original': 'acheter', 'translation': 'kaufen'},
                           {'original': 'donner', 'translation': 'geben'},
                           {'original': 'tenir', 'translation': 'halten'},
                           {'original': 'manger', 'translation': 'essen'},
                           {'original': 'boire', 'translation': 'trinken'},
                           {'original': 'parler', 'translation': 'sprechen'},
                           {'original': 'dire', 'translation': 'sagen'},
                           {'original': 'marcher', 'translation': 'gehen'},
                           {'original': 'se promener', 'translation': 'besichtigen'},
                           {'original': 'aller', 'translation': 'fahren'},
                           {'original': 'partir', 'translation': 'weggehen'},
                           {'original': 'venir', 'translation': 'kommen'},
                           {'original': 'rester', 'translation': 'bleiben'},
                           {'original': 'passer', 'translation': 'vergehen'},
                           {'original': 'entrer', 'translation': 'hereinkommen'},
                           {'original': 'sortir', 'translation': 'auskommen'},
                           {'original': 'courir', 'translation': 'laufen'},
                           {'original': "s'asseoir", 'translation': 'setzen'},
                           {'original': 'dormir', 'translation': 'schlafen'},
                           {'original': 'habiter', 'translation': 'wohnen'}]},
                {'name': 'Pronoms & Lieux',
                 'words': [{'original': 'qui', 'translation': 'wer'},
                           {'original': 'personne', 'translation': 'niemand'},
                           {'original': "quelqu'un", 'translation': 'jemand'},
                           {'original': 'tout le monde', 'translation': 'alle'},
                           {'original': 'ich', 'translation': 'bin habe'},
                           {'original': 'du', 'translation': 'bist hast'},
                           {'original': 'er', 'translation': 'ist hat'},
                           {'original': 'es', 'translation': 'ist hat'},
                           {'original': 'sie', 'translation': 'ist hat'},
                           {'original': 'wir', 'translation': 'sind haben'},
                           {'original': 'ihr', 'translation': 'seid habt'},
                           {'original': 'sie', 'translation': 'sind haben'},
                           {'original': 'mon', 'translation': 'mein'},
                           {'original': 'ton', 'translation': 'dein'},
                           {'original': 'son', 'translation': 'sein'},
                           {'original': 'notre', 'translation': 'unser'},
                           {'original': 'votre', 'translation': 'ihr'},
                           {'original': 'leurs', 'translation': 'ihre'},
                           {'original': 'ceci', 'translation': 'das'},
                           {'original': 'de', 'translation': 'von'},
                           {'original': 'enfant', 'translation': 'das Kind'},
                           {'original': 'fils', 'translation': 'Sohn'},
                           {'original': 'fille', 'translation': 'Tochter'},
                           {'original': 'mère', 'translation': 'die Muter'},
                           {'original': 'père', 'translation': 'der Vater'},
                           {'original': 'frère', 'translation': 'der Bruder'},
                           {'original': 'soeur', 'translation': 'die Schwester'},
                           {'original': 'mari', 'translation': 'Mann'},
                           {'original': 'femme', 'translation': 'Ehefrau'},
                           {'original': 'ami(e)', 'translation': 'freund(in)'}]},
                {'name': 'Maison & Ville',
                 'words': [{'original': 'où', 'translation': 'wo'},
                           {'original': 'quelque part', 'translation': 'irgendwo'},
                           {'original': 'partout', 'translation': 'überall'},
                           {'original': 'ici', 'translation': 'hier, da'},
                           {'original': 'là-bas', 'translation': 'dort'},
                           {'original': 'vers', 'translation': 'nach'},
                           {'original': 'à droite', 'translation': 'rechts'},
                           {'original': 'à gauche', 'translation': 'links'},
                           {'original': 'tout droit', 'translation': 'geradeaus'},
                           {'original': 'devant', 'translation': 'an, vor'},
                           {'original': 'derrière', 'translation': 'hinter'},
                           {'original': 'dessous', 'translation': 'unter'},
                           {'original': 'en haut', 'translation': 'oben'},
                           {'original': 'dessus', 'translation': 'über'},
                           {'original': 'dans', 'translation': 'in'},
                           {'original': 'mer', 'translation': 'das Meer'},
                           {'original': 'soleil', 'translation': 'die Sonne'},
                           {'original': 'ville', 'translation': 'die Stadt'},
                           {'original': 'maison', 'translation': 'das Haus'},
                           {'original': 'magasin', 'translation': 'das Geschäft'},
                           {'original': 'école', 'translation': 'Schule'},
                           {'original': 'lit', 'translation': 'das Bett'},
                           {'original': 'chambre', 'translation': 'das Zimmer'},
                           {'original': 'salle de bain', 'translation': 'das Bad'},
                           {'original': 'cuisine', 'translation': 'die Küche'},
                           {'original': 'table', 'translation': 'der Tisch'},
                           {'original': 'chaise', 'translation': 'der Stuhl'},
                           {'original': 'avion', 'translation': 'das Flugzeug'},
                           {'original': 'voiture', 'translation': 'das Auto'},
                           {'original': 'bus', 'translation': 'Bus'},
                           {'original': 'train', 'translation': 'der Zug'},
                           {'original': 'Allemagne', 'translation': 'Deutschland'},
                           {'original': 'France', 'translation': 'Frankreich'}]},
                {'name': 'Temps',
                 'words': [{'original': 'quand', 'translation': 'wann'},
                           {'original': 'le temps', 'translation': 'die Zeit'},
                           {'original': 'jamais', 'translation': 'nie(mals)'},
                           {'original': 'souvent', 'translation': 'oft'},
                           {'original': 'toujours', 'translation': 'immer'},
                           {'original': 'maintenant', 'translation': 'jetzt'},
                           {'original': 'tout de suite', 'translation': 'sofort, gleich'},
                           {'original': 'avant', 'translation': 'vor'},
                           {'original': 'après', 'translation': 'nach'},
                           {'original': 'bientôt', 'translation': 'bald'},
                           {'original': 'tôt', 'translation': 'früh'},
                           {'original': 'tard', 'translation': 'spät'},
                           {'original': 'dernier', 'translation': 'letzte'},
                           {'original': 'prochain', 'translation': 'nächste'},
                           {'original': 'matin', 'translation': 'morgen'},
                           {'original': 'soir', 'translation': 'abend'},
                           {'original': 'nuit', 'translation': 'nacht'},
                           {'original': "aujourd'hui", 'translation': 'heute'},
                           {'original': 'demain', 'translation': 'morgen'},
                           {'original': 'hier', 'translation': 'gestern'},
                           {'original': 'année', 'translation': 'das Jahr'},
                           {'original': 'mois', 'translation': 'der Monat'},
                           {'original': 'semaine', 'translation': 'die Woche'},
                           {'original': 'jour', 'translation': 'der Tag'},
                           {'original': 'heure', 'translation': 'die Uhr'},
                           {'original': 'minute', 'translation': 'die Minute'},
                           {'original': 'couleur', 'translation': 'Farbe'},
                           {'original': 'bleu', 'translation': 'blau'},
                           {'original': 'rouge', 'translation': 'rot'},
                           {'original': 'vert', 'translation': 'grün'},
                           {'original': 'jaune', 'translation': 'gelb'},
                           {'original': 'blanc', 'translation': 'weiss'},
                           {'original': 'noir', 'translation': 'schwarz'}]},
                {'name': 'Adjectifs',
                 'words': [{'original': 'comment', 'translation': 'wie'},
                           {'original': 'jeune', 'translation': 'jung'},
                           {'original': 'fatigué', 'translation': 'müde'},
                           {'original': 'important', 'translation': 'bedeutend'},
                           {'original': 'nouveau', 'translation': 'neu'},
                           {'original': 'ancien', 'translation': 'alt'},
                           {'original': 'célèbre', 'translation': 'berühmt'},
                           {'original': 'beau', 'translation': 'schön'},
                           {'original': 'mauvais', 'translation': 'slecht'},
                           {'original': 'gentil', 'translation': 'nett'},
                           {'original': 'grand', 'translation': 'gross'},
                           {'original': 'petit', 'translation': 'klein'},
                           {'original': 'loin', 'translation': 'weit'},
                           {'original': 'près', 'translation': 'nah'},
                           {'original': 'bon', 'translation': 'gut'},
                           {'original': 'chaud', 'translation': 'warm'},
                           {'original': 'froid', 'translation': 'kalt'},
                           {'original': 'haut', 'translation': 'hoch'},
                           {'original': 'interdit', 'translation': 'verboten'},
                           {'original': 'vite', 'translation': 'schnell'},
                           {'original': 'lentement', 'translation': 'langsam'},
                           {'original': 'vide', 'translation': 'leer'},
                           {'original': 'plein', 'translation': 'voll'},
                           {'original': 'propre', 'translation': 'sauber'},
                           {'original': 'sale', 'translation': 'schmutzig'},
                           {'original': 'difficile', 'translation': 'schwierig'},
                           {'original': 'facile', 'translation': 'einfach'},
                           {'original': 'autre', 'translation': 'anders'},
                           {'original': 'comme', 'translation': 'als'},
                           {'original': 'aussi', 'translation': 'auch'},
                           {'original': 'avec (moi)', 'translation': 'mit (mir)'},
                           {'original': 'sans (moi)', 'translation': 'ohne (mich)'},
                           {'original': 'seul', 'translation': 'allein'},
                           {'original': 'ensemble', 'translation': 'zusammen'},
                           {'original': 'pour (moi)', 'translation': 'für (mich)'}]},
                {'name': 'Corps & Objets',
                 'words': [{'original': 'tête', 'translation': 'der Kopf'},
                           {'original': 'cheveux', 'translation': 'die Haare'},
                           {'original': 'oeil', 'translation': 'das Auge'},
                           {'original': 'oreille', 'translation': 'das Ohr'},
                           {'original': 'nez', 'translation': 'die Nase'},
                           {'original': 'bouche', 'translation': 'der Mund'},
                           {'original': 'dent', 'translation': 'der Zahn'},
                           {'original': 'main', 'translation': 'die Hand'},
                           {'original': 'pied', 'translation': 'der Fuss'}]},
                {'name': 'Chiffres & Quantité',
                 'words': [{'original': 'combien', 'translation': 'wie viel'},
                           {'original': 'un peu', 'translation': 'ein bisschen'},
                           {'original': 'beaucoup', 'translation': 'viel'},
                           {'original': 'moins', 'translation': 'weninger ... als'},
                           {'original': 'plus', 'translation': 'mehr ... als'},
                           {'original': 'trop', 'translation': 'zu'},
                           {'original': '1', 'translation': 'ein'},
                           {'original': '2', 'translation': 'zwei'},
                           {'original': '3', 'translation': 'drei'},
                           {'original': '4', 'translation': 'vier'},
                           {'original': '5', 'translation': 'fünf'},
                           {'original': '6', 'translation': 'sechs'},
                           {'original': '7', 'translation': 'sieben'},
                           {'original': '8', 'translation': 'acht'},
                           {'original': '9', 'translation': 'neun'},
                           {'original': '10', 'translation': 'zehn'},
                           {'original': '11', 'translation': 'elf'},
                           {'original': '12', 'translation': 'zwolf'},
                           {'original': '13', 'translation': 'dreizehn'},
                           {'original': '20', 'translation': 'zwanzig'},
                           {'original': '30', 'translation': 'dreizig'},
                           {'original': '100', 'translation': 'hundert'},
                           {'original': '1000', 'translation': 'tausend'},
                           {'original': 'mais', 'translation': 'aber'},
                           {'original': 'ou', 'translation': 'oder'},
                           {'original': 'et', 'translation': 'und'},
                           {'original': 'donc', 'translation': 'denn'},
                           {'original': 'puis', 'translation': 'dann'},
                           {'original': 'pourquoi', 'translation': 'warum'},
                           {'original': 'parce que', 'translation': 'weil'},
                           {'original': 'alors', 'translation': 'also'},
                           {'original': 'quel(le,s)', 'translation': 'welche(r,s)'}]},
                {'name': 'Politesse',
                 'words': [{'original': 'bienvenu', 'translation': 'willkommen'},
                           {'original': 'bonjour', 'translation': 'guten tag'},
                           {'original': 'salut', 'translation': 'hallo'},
                           {'original': 'bonsoir', 'translation': 'guten Abend'},
                           {'original': 'bonne nuit', 'translation': 'gute Nacht'},
                           {'original': 'comment vas tu', 'translation': "wie geht's"},
                           {'original': 'je vais bien', 'translation': 'es geht mir gut'},
                           {'original': 'quoi de neuf', 'translation': 'gibt es etwas Neues'},
                           {'original': 'au revoir', 'translation': 'auf Wiedersehen'},
                           {'original': 'à plus tard', 'translation': 'bis bald'},
                           {'original': "s'il vous plaît", 'translation': 'bitte'},
                           {'original': 'merci', 'translation': 'danke'},
                           {'original': 'de rien', 'translation': 'keine ursache'},
                           {'original': 'désolé', 'translation': 'es tut mir Lied'},
                           {'original': 'pardon', 'translation': 'Entschuldigung'},
                           {'original': 'excusez moi', 'translation': 'entschuldigen sie'},
                           {'original': "c'est pas grave", 'translation': 'das macht nichts'},
                           {'original': 'félicitations', 'translation': 'Glückwünsche'},
                           {'original': 'comment vous appelez vous?',
                            'translation': 'wie heissen sie?'},
                           {'original': 'enchanté', 'translation': 'angenehm'},
                           {'original': 'bon appétit', 'translation': 'guten Appetit'},
                           {'original': 'santé!', 'translation': 'Prost'},
                           {'original': "c'est bon", 'translation': 'es schmeckt'},
                           {'original': "l'addition", 'translation': 'Rechnung'},
                           {'original': 'attention', 'translation': 'Vorsicht'},
                           {'original': 'je ne comprend pas',
                            'translation': 'ich verstehe nicht'}]}]}
