# Auto-generated from chat/vocabulary.py

LANGUAGE_DATA = {'display_name': 'Italien',
 'categories': [{'name': 'Alimentation',
                 'words': [{'original': 'nourriture', 'translation': 'cibo'},
                           {'original': 'fruit', 'translation': 'frutta'},
                           {'original': 'légumes', 'translation': 'verdure'},
                           {'original': 'pain', 'translation': 'pane'},
                           {'original': 'fromage', 'translation': 'formaggio'},
                           {'original': 'viande', 'translation': 'carne'},
                           {'original': 'poisson', 'translation': 'pesce'},
                           {'original': 'sel', 'translation': 'sale'},
                           {'original': 'sucre', 'translation': 'zucchero'},
                           {'original': 'eau', 'translation': 'acqua'},
                           {'original': 'lait', 'translation': 'latte'},
                           {'original': 'café', 'translation': 'caffe'},
                           {'original': 'thé', 'translation': 'te'},
                           {'original': 'bière', 'translation': 'birra'},
                           {'original': 'vin', 'translation': 'vino'},
                           {'original': 'riz', 'translation': 'riso'},
                           {'original': 'huile', 'translation': 'olio'},
                           {'original': 'animal', 'translation': 'animale'}]},
                {'name': 'Expressions & Pensée',
                 'words': [{'original': 'quoi?', 'translation': 'che?'},
                           {'original': 'rien', 'translation': 'niente'},
                           {'original': 'quelque chose', 'translation': 'qualcosa'},
                           {'original': 'tout', 'translation': 'tutto'},
                           {'original': 'il y a', 'translation': "c'e"},
                           {'original': "il n'y a pas", 'translation': "non c'e"},
                           {'original': "c'est", 'translation': 'e'},
                           {'original': 'je veux', 'translation': 'voglio'},
                           {'original': "j'aime", 'translation': 'mi piace'},
                           {'original': 'je dois', 'translation': 'devo'},
                           {'original': 'je peux', 'translation': 'posso'},
                           {'original': 'je pense', 'translation': 'penso'},
                           {'original': 'peut-être', 'translation': 'forse'},
                           {'original': 'et', 'translation': 'e'},
                           {'original': 'ou', 'translation': 'o'},
                           {'original': 'mais', 'translation': 'ma'},
                           {'original': 'parce que', 'translation': 'perche'},
                           {'original': 'pour', 'translation': 'per'},
                           {'original': 'aimer', 'translation': 'amare'},
                           {'original': 'pouvoir', 'translation': 'potere'},
                           {'original': 'pourquoi', 'translation': 'perche'}]},
                {'name': "Verbes d'action",
                 'words': [{'original': 'faire', 'translation': 'fare'},
                           {'original': 'aller', 'translation': 'andare'},
                           {'original': 'venir', 'translation': 'venire'},
                           {'original': 'partir', 'translation': 'partire'},
                           {'original': 'attendre', 'translation': 'aspettare'},
                           {'original': 'écrire', 'translation': 'scrivere'},
                           {'original': 'lire', 'translation': 'leggere'},
                           {'original': 'commencer', 'translation': 'iniziare'},
                           {'original': 'finir', 'translation': 'finire'},
                           {'original': 'entrer', 'translation': 'entrare'},
                           {'original': 'sortir', 'translation': 'uscire'},
                           {'original': 'courir', 'translation': 'correre'},
                           {'original': 'voir', 'translation': 'vedere'},
                           {'original': 'écouter', 'translation': 'ascoltare'},
                           {'original': 'boire', 'translation': 'bere'},
                           {'original': 'manger', 'translation': 'mangiare'},
                           {'original': 'parler', 'translation': 'parlare'},
                           {'original': 'comprendre', 'translation': 'capire'}]},
                {'name': 'Pronoms & Lieux',
                 'words': [{'original': 'qui', 'translation': 'chi'},
                           {'original': 'moi', 'translation': 'io'},
                           {'original': 'toi', 'translation': 'tu'},
                           {'original': 'il/elle', 'translation': 'lui/lei'},
                           {'original': 'nous', 'translation': 'noi'},
                           {'original': 'vous', 'translation': 'voi/Lei'},
                           {'original': 'ils', 'translation': 'loro'},
                           {'original': 'ceci', 'translation': 'questo'},
                           {'original': 'cela', 'translation': 'quello'},
                           {'original': 'où', 'translation': 'dove'},
                           {'original': 'ici', 'translation': 'qui'},
                           {'original': 'là', 'translation': 'la'},
                           {'original': 'en haut', 'translation': 'in alto'},
                           {'original': 'devant', 'translation': 'davanti'},
                           {'original': 'derrière', 'translation': 'dietro'},
                           {'original': 'à gauche', 'translation': 'a sinistra'},
                           {'original': 'à droite', 'translation': 'a destra'},
                           {'original': 'dans', 'translation': 'in'},
                           {'original': 'de', 'translation': 'di'}]},
                {'name': 'Maison & Ville',
                 'words': [{'original': 'maison', 'translation': 'casa'},
                           {'original': 'cuisine', 'translation': 'cucina'},
                           {'original': 'chambre', 'translation': 'camera'},
                           {'original': 'lit', 'translation': 'letto'},
                           {'original': 'salle de bain', 'translation': 'bagno'},
                           {'original': 'table', 'translation': 'tavolo'},
                           {'original': 'chaise', 'translation': 'sedia'},
                           {'original': 'ville', 'translation': 'citta'},
                           {'original': 'rue', 'translation': 'strada'},
                           {'original': 'magasin', 'translation': 'negozio'},
                           {'original': 'arbre', 'translation': 'albero'},
                           {'original': 'montagne', 'translation': 'montagna'},
                           {'original': 'mer', 'translation': 'mare'},
                           {'original': 'soleil', 'translation': 'sole'},
                           {'original': 'voiture', 'translation': 'macchina'},
                           {'original': 'bus', 'translation': 'autobus'},
                           {'original': 'train', 'translation': 'treno'},
                           {'original': 'voyage', 'translation': 'viaggio'}]},
                {'name': 'Temps',
                 'words': [{'original': 'quand', 'translation': 'quando'},
                           {'original': 'temps', 'translation': 'tempo'},
                           {'original': 'jamais', 'translation': 'mai'},
                           {'original': 'parfois', 'translation': 'a volte'},
                           {'original': 'souvent', 'translation': 'spesso'},
                           {'original': 'toujours', 'translation': 'sempre'},
                           {'original': 'maintenant', 'translation': 'adesso'},
                           {'original': 'avant', 'translation': 'prima'},
                           {'original': 'après', 'translation': 'dopo'},
                           {'original': 'matin', 'translation': 'mattina'},
                           {'original': 'après-midi', 'translation': 'pomeriggio'},
                           {'original': 'soir', 'translation': 'sera'},
                           {'original': 'nuit', 'translation': 'notte'},
                           {'original': "aujourd'hui", 'translation': 'oggi'},
                           {'original': 'demain', 'translation': 'domani'},
                           {'original': 'hier', 'translation': 'ieri'},
                           {'original': 'année', 'translation': 'anno'},
                           {'original': 'mois', 'translation': 'mese'}]},
                {'name': 'Adjectifs',
                 'words': [{'original': 'bon', 'translation': 'buono'},
                           {'original': 'mauvais', 'translation': 'cattivo'},
                           {'original': 'beau', 'translation': 'bello'},
                           {'original': 'grand', 'translation': 'grande'},
                           {'original': 'petit', 'translation': 'piccolo'},
                           {'original': 'chaud', 'translation': 'caldo'},
                           {'original': 'froid', 'translation': 'freddo'},
                           {'original': 'vite', 'translation': 'veloce'},
                           {'original': 'lent', 'translation': 'lento'},
                           {'original': 'nouveau', 'translation': 'nuovo'},
                           {'original': 'ancien', 'translation': 'vecchio'},
                           {'original': 'facile', 'translation': 'facile'},
                           {'original': 'difficile', 'translation': 'difficile'},
                           {'original': 'important', 'translation': 'importante'},
                           {'original': 'propre', 'translation': 'pulito'},
                           {'original': 'sale', 'translation': 'sporco'},
                           {'original': 'près', 'translation': 'vicino'},
                           {'original': 'loin', 'translation': 'lontano'}]},
                {'name': 'Chiffres & Quantité',
                 'words': [{'original': 'combien', 'translation': 'quanto'},
                           {'original': 'un peu', 'translation': 'un po'},
                           {'original': 'beaucoup', 'translation': 'molto'},
                           {'original': 'moins', 'translation': 'meno'},
                           {'original': 'plus', 'translation': 'piu'},
                           {'original': 'très', 'translation': 'molto'},
                           {'original': 'trop', 'translation': 'troppo'},
                           {'original': '0', 'translation': 'zero'},
                           {'original': '1', 'translation': 'uno'},
                           {'original': '2', 'translation': 'due'},
                           {'original': '3', 'translation': 'tre'},
                           {'original': '4', 'translation': 'quattro'},
                           {'original': '5', 'translation': 'cinque'},
                           {'original': '6', 'translation': 'sei'},
                           {'original': '7', 'translation': 'sette'},
                           {'original': '8', 'translation': 'otto'},
                           {'original': '9', 'translation': 'nove'},
                           {'original': '10', 'translation': 'dieci'}]},
                {'name': 'Politesse',
                 'words': [{'original': 'oui', 'translation': 'si'},
                           {'original': 'non', 'translation': 'no'},
                           {'original': 'bonjour', 'translation': 'ciao'},
                           {'original': 'salut', 'translation': 'ciao'},
                           {'original': 'bonsoir', 'translation': 'buonasera'},
                           {'original': 'bonne nuit', 'translation': 'buonanotte'},
                           {'original': 'au revoir', 'translation': 'arrivederci'},
                           {'original': "s'il vous plaît", 'translation': 'per favore'},
                           {'original': 'merci', 'translation': 'grazie'},
                           {'original': 'de rien', 'translation': 'prego'},
                           {'original': 'excusez-moi', 'translation': 'mi scusi'},
                           {'original': 'pardon', 'translation': 'scusa'},
                           {'original': 'comment ça va?', 'translation': 'come stai?'},
                           {'original': 'je vais bien', 'translation': 'sto bene'},
                           {'original': 'je ne comprends pas', 'translation': 'non capisco'},
                           {'original': 'parlez plus lentement',
                            'translation': 'parli piu lentamente'},
                           {'original': 'comment vous appelez-vous?',
                            'translation': 'come si chiama?'},
                           {'original': "je m'appelle []", 'translation': 'mi chiamo []'}]},
                {'name': 'Divers',
                 'words': [{'original': 'enfant', 'translation': 'bambino/bambina'},
                           {'original': 'garçon', 'translation': 'ragazzo'},
                           {'original': 'fille', 'translation': 'ragazza'},
                           {'original': 'mère', 'translation': 'madre'},
                           {'original': 'père', 'translation': 'padre'},
                           {'original': 'frère', 'translation': 'fratello'},
                           {'original': 'soeur', 'translation': 'sorella'},
                           {'original': 'ami(e)', 'translation': 'amico/a'},
                           {'original': 'mari', 'translation': 'marito'},
                           {'original': 'femme', 'translation': 'moglie'},
                           {'original': 'bon appétit', 'translation': 'buon appetito'},
                           {'original': 'santé!', 'translation': 'salute!'},
                           {'original': 'travail', 'translation': 'lavoro'},
                           {'original': 'argent', 'translation': 'denaro'},
                           {'original': 'livre', 'translation': 'libro'},
                           {'original': 'television', 'translation': 'televisione'},
                           {'original': 'vêtement', 'translation': 'vestito'},
                           {'original': 'tête', 'translation': 'testa'},
                           {'original': 'cheveux', 'translation': 'capelli'},
                           {'original': 'oeil', 'translation': 'occhio'},
                           {'original': 'oreille', 'translation': 'orecchio'},
                           {'original': 'nez', 'translation': 'naso'},
                           {'original': 'bouche', 'translation': 'bocca'},
                           {'original': 'dent', 'translation': 'dente'},
                           {'original': 'main', 'translation': 'mano'},
                           {'original': 'pied', 'translation': 'piede'},
                           {'original': 'quelques chose', 'translation': 'qualcosa'},
                           {'original': 'chaque', 'translation': 'ogni'},
                           {'original': "c'est possible", 'translation': 'e possibile'},
                           {'original': 'quel(le,s)', 'translation': 'quale'},
                           {'original': 'quelle sorte', 'translation': 'che tipo'},
                           {'original': "c'est pas la peine", 'translation': 'non serve'},
                           {'original': 'je sais que', 'translation': 'so che'},
                           {'original': 'donc', 'translation': 'quindi'},
                           {'original': 'puis', 'translation': 'poi'},
                           {'original': 'alors', 'translation': 'allora'},
                           {'original': 'par example', 'translation': 'per esempio'},
                           {'original': 'marcher', 'translation': 'camminare'},
                           {'original': 'se promener', 'translation': 'passeggiare'},
                           {'original': 'rester', 'translation': 'restare'},
                           {'original': 'passer', 'translation': 'passare'},
                           {'original': 'tourner', 'translation': 'girare'},
                           {'original': "s'asseoir", 'translation': 'sedersi'},
                           {'original': 'regarder', 'translation': 'guardare'},
                           {'original': 'prendre', 'translation': 'prendere'},
                           {'original': 'acheter', 'translation': 'comprare'},
                           {'original': 'tenir', 'translation': 'tenere'},
                           {'original': 'dormir', 'translation': 'dormire'},
                           {'original': 'travailler', 'translation': 'lavorare'},
                           {'original': 'penser', 'translation': 'pensare'},
                           {'original': 'chercher', 'translation': 'cercare'},
                           {'original': 'donner', 'translation': 'dare'},
                           {'original': 'avoir', 'translation': 'avere'},
                           {'original': 'payer', 'translation': 'pagare'},
                           {'original': 'dire', 'translation': 'dire'},
                           {'original': 'demander', 'translation': 'chiedere'},
                           {'original': 'apprendre', 'translation': 'imparare'},
                           {'original': 'fils', 'translation': 'figlio'},
                           {'original': 'mon épouse', 'translation': 'mia moglie'},
                           {'original': 'personne', 'translation': 'nessuno'},
                           {'original': "quelqu'un", 'translation': 'qualcuno'},
                           {'original': 'tout le monde', 'translation': 'tutti'},
                           {'original': 'humain', 'translation': 'umano'},
                           {'original': 'nulle-part', 'translation': 'da nessuna parte'},
                           {'original': 'quelques-part', 'translation': 'da qualche parte'},
                           {'original': 'partout', 'translation': 'ovunque'},
                           {'original': 'là-bas', 'translation': 'laggiu'},
                           {'original': 'en bas', 'translation': 'in basso'},
                           {'original': "l'intérieur", 'translation': 'interno'},
                           {'original': "l'exterieur", 'translation': 'esterno'},
                           {'original': 'tout droit', 'translation': 'dritto'},
                           {'original': 'dessus', 'translation': 'sopra'},
                           {'original': 'vers', 'translation': 'verso'},
                           {'original': 'à côté', 'translation': 'accanto'},
                           {'original': 'forêt', 'translation': 'foresta'},
                           {'original': 'avion', 'translation': 'aereo'},
                           {'original': 'transport', 'translation': 'trasporto'},
                           {'original': 'pays', 'translation': 'paese'},
                           {'original': 'France', 'translation': 'francia'},
                           {'original': 'Angleterre', 'translation': 'inghilterra'},
                           {'original': 'cette année', 'translation': "quest'anno"},
                           {'original': 'an', 'translation': 'anno'},
                           {'original': 'semaine', 'translation': 'settimana'},
                           {'original': 'jour', 'translation': 'giorno'},
                           {'original': 'heure', 'translation': 'ora'},
                           {'original': 'minute', 'translation': 'minuto'},
                           {'original': 'seconde', 'translation': 'secondo'},
                           {'original': 'tout de suite', 'translation': 'subito'},
                           {'original': 'tôt', 'translation': 'presto'},
                           {'original': 'bientôt', 'translation': 'presto'},
                           {'original': 'prochain', 'translation': 'prossimo'},
                           {'original': 'tard', 'translation': 'tardi'},
                           {'original': 'dernier', 'translation': 'ultimo'},
                           {'original': 'déjà', 'translation': 'gia'},
                           {'original': 'depuis', 'translation': 'da'},
                           {'original': "jusqu'à", 'translation': 'fino a'},
                           {'original': 'pas encore', 'translation': 'non ancora'},
                           {'original': 'de nouveau', 'translation': 'di nuovo'},
                           {'original': 'comment', 'translation': 'come'},
                           {'original': 'vide', 'translation': 'vuoto'},
                           {'original': 'plein', 'translation': 'pieno'},
                           {'original': 'ouvert', 'translation': 'aperto'},
                           {'original': 'fermé', 'translation': 'chiuso'},
                           {'original': "(j'ai) faim", 'translation': '(ho) fame'},
                           {'original': 'malade', 'translation': 'malato'},
                           {'original': 'content', 'translation': 'contento'},
                           {'original': 'fatigué', 'translation': 'stanco'},
                           {'original': 'interdit', 'translation': 'vietato'},
                           {'original': 'prêt', 'translation': 'pronto'},
                           {'original': 'bien', 'translation': 'bene'},
                           {'original': 'jeune', 'translation': 'giovane'},
                           {'original': 'célèbre', 'translation': 'famoso'},
                           {'original': 'gentil', 'translation': 'gentile'},
                           {'original': 'intéressant', 'translation': 'interessante'},
                           {'original': 'cher', 'translation': 'caro'},
                           {'original': 'autre', 'translation': 'altro'},
                           {'original': 'different', 'translation': 'diverso'},
                           {'original': 'comme', 'translation': 'come'},
                           {'original': 'comme ça', 'translation': 'cosi'},
                           {'original': 'ainsi', 'translation': 'cosi'},
                           {'original': 'aussi', 'translation': 'anche'},
                           {'original': 'avec', 'translation': 'con'},
                           {'original': 'sans', 'translation': 'senza'},
                           {'original': 'seul', 'translation': 'solo'},
                           {'original': 'ensemble', 'translation': 'insieme'},
                           {'original': 'haut', 'translation': 'alto'},
                           {'original': 'bas', 'translation': 'basso'},
                           {'original': 'lourd', 'translation': 'pesante'},
                           {'original': 'couleur', 'translation': 'colore'},
                           {'original': 'bleu', 'translation': 'blu'},
                           {'original': 'rouge', 'translation': 'rosso'},
                           {'original': 'vert', 'translation': 'verde'},
                           {'original': 'jaune', 'translation': 'giallo'},
                           {'original': 'blanc', 'translation': 'bianco'},
                           {'original': 'noir', 'translation': 'nero'},
                           {'original': '11', 'translation': 'undici'},
                           {'original': '12', 'translation': 'dodici'},
                           {'original': 'environ', 'translation': 'circa'},
                           {'original': 'assez', 'translation': 'abbastanza'},
                           {'original': 'le plus', 'translation': 'il piu'},
                           {'original': '?', 'translation': '?'},
                           {'original': "y a t'il?", 'translation': "c'e?"},
                           {'original': "ce n'est pas []", 'translation': 'non e []'},
                           {'original': "j'aime []", 'translation': 'mi piace []'},
                           {'original': 'je dois []', 'translation': 'devo []'},
                           {'original': "j'ai besoin de []", 'translation': 'ho bisogno di []'},
                           {'original': 'je vais []', 'translation': 'vado []'},
                           {'original': 'je connais []', 'translation': 'conosco []'},
                           {'original': 'je peux []', 'translation': 'posso []'},
                           {'original': 'je pense que []', 'translation': 'penso che []'},
                           {'original': 'présent', 'translation': 'presente'},
                           {'original': 'neg. prés.', 'translation': 'neg. presente'},
                           {'original': 'trouver []', 'translation': 'trovare []'},
                           {'original': 'habiter à []', 'translation': 'abitare a []'},
                           {'original': 'de []', 'translation': 'di []'},
                           {'original': 'ce [] ci', 'translation': 'questo []'},
                           {'original': 'ce [] là', 'translation': 'quel [] li'},
                           {'original': 'droite (de [])', 'translation': 'destra (di [])'},
                           {'original': 'pour []', 'translation': 'per []'},
                           {'original': '20', 'translation': 'venti'},
                           {'original': '100', 'translation': 'cento'},
                           {'original': '1000', 'translation': 'mille'},
                           {'original': '10000', 'translation': 'diecimila'},
                           {'original': 'plus que []', 'translation': 'piu di []'},
                           {'original': 'bienvenue', 'translation': 'benvenuto'},
                           {'original': 'comment vas tu', 'translation': 'come stai'},
                           {'original': 'merci, je vais bien', 'translation': 'grazie, sto bene'},
                           {'original': 'comment vous appelez vous?',
                            'translation': 'come si chiama?'},
                           {'original': "je m'appele []", 'translation': 'mi chiamo []'},
                           {'original': "d'où venez vous?", 'translation': 'da dove viene?'},
                           {'original': 'je suis de []', 'translation': 'sono di []'},
                           {'original': 'enchanté', 'translation': 'piacere'},
                           {'original': 'aurevoir', 'translation': 'arrivederci'},
                           {'original': 'écrivez le', 'translation': 'lo scriva'},
                           {'original': 'donnez moi []', 'translation': 'mi dia []'},
                           {'original': 'je vous en prie', 'translation': 'prego'},
                           {'original': 'excusez moi', 'translation': 'mi scusi'},
                           {'original': 'pas de problème', 'translation': 'nessun problema'},
                           {'original': 'voici', 'translation': 'ecco'},
                           {'original': "n'est ce pas", 'translation': 'vero?'},
                           {'original': "ne t'inquiète pas", 'translation': 'non preoccuparti'},
                           {'original': "je ne sais pas, je n'ai pas compris",
                            'translation': 'non lo so, non ho capito'}]}]}
