# Auto-generated from chat/vocabulary.py

LANGUAGE_DATA = {'display_name': 'Japonais',
 'categories': [{'name': 'Alimentation',
                 'words': [{'original': 'nourriture', 'translation': 'tabemono'},
                           {'original': 'fruit', 'translation': 'kudamono'},
                           {'original': 'légumes', 'translation': 'yasai'},
                           {'original': 'fromage', 'translation': 'chiizu'},
                           {'original': 'pain', 'translation': 'pan'},
                           {'original': 'animal', 'translation': 'doobutsu'},
                           {'original': 'viande', 'translation': 'niku'},
                           {'original': 'poisson', 'translation': 'sakana'},
                           {'original': 'sucre', 'translation': 'satoo'},
                           {'original': 'riz', 'translation': 'kome'},
                           {'original': 'sel', 'translation': 'shio'},
                           {'original': 'café', 'translation': 'koohii'},
                           {'original': 'thé', 'translation': 'ocha'},
                           {'original': 'eau', 'translation': 'mizu'},
                           {'original': 'lait', 'translation': 'gyuunyuu'},
                           {'original': 'huile', 'translation': 'abura'},
                           {'original': 'bière', 'translation': 'biiru'},
                           {'original': 'vin', 'translation': 'wain'}]},
                {'name': 'Corps & Objets',
                 'words': [{'original': 'travail', 'translation': 'shigoto'},
                           {'original': 'argent', 'translation': 'o kane'},
                           {'original': 'livre', 'translation': 'hon'},
                           {'original': 'television', 'translation': 'terebi'},
                           {'original': 'vêtement', 'translation': 'yoofuku'},
                           {'original': 'tête', 'translation': 'atama'},
                           {'original': 'cheveux', 'translation': 'kami no ke'},
                           {'original': 'oeil', 'translation': 'me'},
                           {'original': 'oreille', 'translation': 'mimi'},
                           {'original': 'nez', 'translation': 'ha'},
                           {'original': 'bouche', 'translation': 'kuchi'},
                           {'original': 'dent', 'translation': 'ha'},
                           {'original': 'main', 'translation': 'te'},
                           {'original': 'pied', 'translation': 'ashi'}]},
                {'name': 'Divers',
                 'words': [{'original': 'quoi?', 'translation': 'nani'},
                           {'original': 'rien', 'translation': 'nanimo'},
                           {'original': 'quelques chose', 'translation': 'nanika'},
                           {'original': 'tout', 'translation': 'subete'},
                           {'original': 'chaque', 'translation': 'kaku'},
                           {'original': '?', 'translation': 'ka'},
                           {'original': 'il y a', 'translation': 'arimasu'},
                           {'original': "il n'y a pas", 'translation': 'arimasen'},
                           {'original': "y a t'il?", 'translation': 'arimasu ka?'},
                           {'original': "c'est", 'translation': 'desu'},
                           {'original': "ce n'est pas []", 'translation': '[] dewa arimasen'},
                           {'original': 'je veux', 'translation': '-tai'},
                           {'original': "j'aime []", 'translation': '[] ga suki desu'},
                           {'original': 'je dois []', 'translation': '[] hitsuyoo ga arimasu'},
                           {'original': "j'ai besoin de []", 'translation': '[] ga hitsuyoo'},
                           {'original': "c'est pas la peine", 'translation': 'kekko desu'},
                           {'original': 'je vais []', 'translation': '[] ni ikimasu'},
                           {'original': 'je connais []', 'translation': '[] o shitte iru'},
                           {'original': 'je sais que', 'translation': '[] o shitte imasu'},
                           {'original': 'je peux []', 'translation': '[] koto ga dekimasu'},
                           {'original': 'je pense que []', 'translation': '[] to omoimasu'},
                           {'original': 'peut-être', 'translation': 'tabun'},
                           {'original': "c'est possible", 'translation': 'dekimasu'},
                           {'original': 'mais', 'translation': 'demo'},
                           {'original': 'et', 'translation': 'to'},
                           {'original': 'ou', 'translation': 'soretomo'},
                           {'original': 'donc', 'translation': 'dakara'},
                           {'original': 'puis', 'translation': 'sorekara'},
                           {'original': 'alors', 'translation': '(sore)dewa'},
                           {'original': 'parce que', 'translation': 'kara'},
                           {'original': 'pour', 'translation': 'tame ni'},
                           {'original': 'aimer', 'translation': 'suki'},
                           {'original': 'pouvoir', 'translation': 'dekiru'},
                           {'original': 'par example', 'translation': 'tatoeba'},
                           {'original': 'pourquoi', 'translation': 'naze'},
                           {'original': 'quel(le,s)', 'translation': 'dore'},
                           {'original': 'quelle sorte', 'translation': 'donna'},
                           {'original': 'présent', 'translation': '-(i)masu'},
                           {'original': 'neg. prés.', 'translation': '-(i)masen'}]},
                {'name': "Verbes d'action",
                 'words': [{'original': 'marcher', 'translation': 'aruku'},
                           {'original': 'se promener', 'translation': 'urokku'},
                           {'original': 'aller', 'translation': 'iku'},
                           {'original': 'venir', 'translation': 'k(uru)'},
                           {'original': 'partir', 'translation': 'nokoshimasu'},
                           {'original': 'attendre', 'translation': 'matsu'},
                           {'original': 'écrire', 'translation': 'kaku'},
                           {'original': 'lire', 'translation': 'yomu'},
                           {'original': 'commencer', 'translation': 'hajimeru'},
                           {'original': 'finir', 'translation': 'owaru'},
                           {'original': 'rester', 'translation': 'nokoru'},
                           {'original': 'passer', 'translation': 'yoru'},
                           {'original': 'entrer', 'translation': 'hairu'},
                           {'original': 'tourner', 'translation': 'magaru'},
                           {'original': "s'asseoir", 'translation': 'suwaru'},
                           {'original': 'sortir', 'translation': 'deru'},
                           {'original': 'courir', 'translation': 'hashiru'},
                           {'original': 'regarder', 'translation': 'mimasu'},
                           {'original': 'voir', 'translation': '[] ga miemasu'},
                           {'original': 'écouter', 'translation': 'kiku'},
                           {'original': 'boire', 'translation': 'nomu'},
                           {'original': 'prendre', 'translation': 'toru'},
                           {'original': 'acheter', 'translation': 'kau'},
                           {'original': 'tenir', 'translation': 'hoji shimasu'},
                           {'original': 'manger', 'translation': 'tabemasu'},
                           {'original': 'dormir', 'translation': 'n(eru)'},
                           {'original': 'faire', 'translation': 'suru'},
                           {'original': 'travailler', 'translation': 'hataraite imasu'},
                           {'original': 'penser', 'translation': '[] to omoimasu'},
                           {'original': 'chercher', 'translation': 'sagasu'},
                           {'original': 'trouver []', 'translation': '[] ga mitsukarimasu'},
                           {'original': 'donner', 'translation': 'ataeru'},
                           {'original': 'avoir', 'translation': 'motte imasu'},
                           {'original': 'payer', 'translation': 'harau'},
                           {'original': 'parler', 'translation': 'hanasu'},
                           {'original': 'dire', 'translation': 'iu'},
                           {'original': 'demander', 'translation': 'tatomu'},
                           {'original': 'comprendre', 'translation': 'wakaru'},
                           {'original': 'apprendre', 'translation': 'manabu'},
                           {'original': 'habiter à []', 'translation': '[] ni sunde imasu'}]},
                {'name': 'Social & Famille',
                 'words': [{'original': 'enfant', 'translation': 'kodomo'},
                           {'original': 'garçon', 'translation': 'otoko no ko'},
                           {'original': 'fille', 'translation': 'annanoko'},
                           {'original': 'fils', 'translation': 'musuko'},
                           {'original': 'mère', 'translation': 'okaasan'},
                           {'original': 'père', 'translation': 'otoosan'},
                           {'original': 'frère', 'translation': 'ani'},
                           {'original': 'soeur', 'translation': 'ane'},
                           {'original': 'ami(e)', 'translation': 'yuujin'},
                           {'original': 'mari', 'translation': 'otto'},
                           {'original': 'femme', 'translation': 'tsuma'},
                           {'original': 'mon épouse', 'translation': 'kanai'}]},
                {'name': 'Pronoms & Lieux',
                 'words': [{'original': 'qui', 'translation': 'dare'},
                           {'original': 'personne', 'translation': 'daremo'},
                           {'original': "quelqu'un", 'translation': 'dareka'},
                           {'original': 'tout le monde', 'translation': 'mina'},
                           {'original': 'humain', 'translation': 'jin'},
                           {'original': 'moi', 'translation': 'watashi'},
                           {'original': 'toi', 'translation': 'kimi'},
                           {'original': 'il/elle', 'translation': 'kare/kanojo'},
                           {'original': 'nous', 'translation': 'ware ware'},
                           {'original': 'vous', 'translation': 'anata (kata)'},
                           {'original': 'ils', 'translation': 'karera'},
                           {'original': 'de []', 'translation': '[] no'},
                           {'original': 'ceci', 'translation': 'kore'},
                           {'original': 'cela', 'translation': 'sore'},
                           {'original': 'ce [] ci', 'translation': 'kono'},
                           {'original': 'ce [] là', 'translation': 'sono []'},
                           {'original': 'où', 'translation': 'doko'},
                           {'original': 'nulle-part', 'translation': 'doko ni mo'},
                           {'original': 'quelques-part', 'translation': 'doko ka'},
                           {'original': 'partout', 'translation': 'doko ni demo'},
                           {'original': 'ici', 'translation': 'koko'},
                           {'original': 'là', 'translation': 'soko'},
                           {'original': 'là-bas', 'translation': 'asoko'},
                           {'original': 'en bas', 'translation': 'shita'},
                           {'original': 'en haut', 'translation': 'ue'},
                           {'original': 'devant', 'translation': 'mae'},
                           {'original': 'derrière', 'translation': 'ushiro'},
                           {'original': 'à gauche', 'translation': 'hadari'},
                           {'original': 'droite (de [])', 'translation': '([] no) migi'},
                           {'original': "l'intérieur", 'translation': 'uchi'}]},
                {'name': 'Maison & Ville',
                 'words': [{'original': "l'exterieur", 'translation': 'soto'},
                           {'original': 'tout droit', 'translation': 'masugu'},
                           {'original': 'dessus', 'translation': 'ue'},
                           {'original': 'vers', 'translation': 'mukatte'},
                           {'original': 'à côté', 'translation': 'soba ni'},
                           {'original': 'maison', 'translation': 'ie'},
                           {'original': 'cuisine', 'translation': 'daidokoro'},
                           {'original': 'chambre', 'translation': 'shin shitsu'},
                           {'original': 'lit', 'translation': 'beddo'},
                           {'original': 'salle de bain', 'translation': 'toire'},
                           {'original': 'table', 'translation': 'teeburu'},
                           {'original': 'chaise', 'translation': 'isu'},
                           {'original': 'arbre', 'translation': 'ki'},
                           {'original': 'soleil', 'translation': 'taiyoo'},
                           {'original': 'montagne', 'translation': 'yama'},
                           {'original': 'forêt', 'translation': 'shinrin'},
                           {'original': 'mer', 'translation': 'umi'},
                           {'original': 'ville', 'translation': 'tokai'},
                           {'original': 'rue', 'translation': 'gairo'},
                           {'original': 'magasin', 'translation': 'omise'},
                           {'original': 'avion', 'translation': 'hikooki'},
                           {'original': 'voiture', 'translation': 'kuruma'},
                           {'original': 'bus', 'translation': 'basu'},
                           {'original': 'train', 'translation': 'densha'},
                           {'original': 'transport', 'translation': 'kootsuu'},
                           {'original': 'pays', 'translation': 'kuni'},
                           {'original': 'France', 'translation': 'furansu'},
                           {'original': 'Angleterre', 'translation': 'igirisu'},
                           {'original': 'voyage', 'translation': 'ryokoo'}]},
                {'name': 'Temps',
                 'words': [{'original': 'quand', 'translation': 'itsu'},
                           {'original': 'temps', 'translation': 'jikan'},
                           {'original': 'jamais', 'translation': 'kesshite'},
                           {'original': 'parfois', 'translation': 'tokidoki'},
                           {'original': 'souvent', 'translation': 'shibashiba'},
                           {'original': 'toujours', 'translation': 'tsuneni'},
                           {'original': 'année', 'translation': 'nen'},
                           {'original': 'cette année', 'translation': 'kotoshi'},
                           {'original': 'an', 'translation': 'toshi'},
                           {'original': 'mois', 'translation': 'tsuki'},
                           {'original': 'semaine', 'translation': 'shuu'},
                           {'original': 'jour', 'translation': 'nichi'},
                           {'original': 'heure', 'translation': 'jikan'},
                           {'original': 'minute', 'translation': 'fun'},
                           {'original': 'seconde', 'translation': 'byou'},
                           {'original': 'avant', 'translation': 'mae'},
                           {'original': 'après', 'translation': 'ato'},
                           {'original': 'maintenant', 'translation': 'ima'},
                           {'original': 'après', 'translation': 'ato no'},
                           {'original': 'tout de suite', 'translation': 'sugu'},
                           {'original': 'matin', 'translation': 'gozen'},
                           {'original': 'après-midi', 'translation': 'gogo'}]},
                {'name': 'Temps (suite) & État',
                 'words': [{'original': 'soir', 'translation': 'yuugata'},
                           {'original': 'nuit', 'translation': 'yoru'},
                           {'original': "aujourd'hui", 'translation': 'kyoo'},
                           {'original': 'demain', 'translation': 'ashita'},
                           {'original': 'hier', 'translation': 'kinoo'},
                           {'original': 'tôt', 'translation': 'hayaku'},
                           {'original': 'bientôt', 'translation': 'sugu ni'},
                           {'original': 'prochain', 'translation': 'kondo no, tsugi'},
                           {'original': 'tard', 'translation': 'osoi'},
                           {'original': 'dernier', 'translation': 'saishuu'},
                           {'original': 'déjà', 'translation': 'moo'},
                           {'original': 'depuis', 'translation': 'kara, sonogo'},
                           {'original': "jusqu'à", 'translation': 'made'},
                           {'original': 'pas encore', 'translation': 'mada'},
                           {'original': 'de nouveau', 'translation': 'mata'},
                           {'original': 'comment', 'translation': 'ikaga'},
                           {'original': 'loin', 'translation': 'tooi'},
                           {'original': 'près', 'translation': 'chikai'},
                           {'original': 'vide', 'translation': 'karapo'},
                           {'original': 'plein', 'translation': 'ippai'},
                           {'original': 'ouvert', 'translation': 'aitemasu'},
                           {'original': 'fermé', 'translation': 'heiten'},
                           {'original': 'nouveau', 'translation': 'atarashii'},
                           {'original': 'bon', 'translation': 'oishii'},
                           {'original': 'mauvais', 'translation': 'warui'}]},
                {'name': 'Adjectifs',
                 'words': [{'original': "(j'ai) faim", 'translation': 'onaka (ga akimashita)'},
                           {'original': 'chaud', 'translation': 'atsui'},
                           {'original': 'froid', 'translation': 'samui'},
                           {'original': 'beau', 'translation': 'kirei'},
                           {'original': 'bien', 'translation': '(yo(rosh))ii'},
                           {'original': 'ancien', 'translation': 'furui'},
                           {'original': 'jeune', 'translation': 'wakai'},
                           {'original': 'malade', 'translation': 'byooki'},
                           {'original': 'vite', 'translation': 'hayai'},
                           {'original': 'lent', 'translation': 'osoi'},
                           {'original': 'célèbre', 'translation': 'yuumei'},
                           {'original': 'content', 'translation': 'ureshii'},
                           {'original': 'gentil', 'translation': 'yasashii'},
                           {'original': 'intéressant', 'translation': 'omoshiroi'},
                           {'original': 'fatigué', 'translation': 'tsukata'},
                           {'original': 'interdit', 'translation': 'kinshi'},
                           {'original': 'prêt', 'translation': 'yooi'},
                           {'original': 'sale', 'translation': 'yogoreteiru'},
                           {'original': 'propre', 'translation': 'kirei'},
                           {'original': 'haut', 'translation': 'takai'},
                           {'original': 'bas', 'translation': 'hikui'},
                           {'original': 'facile', 'translation': 'kantan'},
                           {'original': 'difficile', 'translation': 'muzukashii'},
                           {'original': 'important', 'translation': 'juuyoo'},
                           {'original': 'cher', 'translation': 'takai'}]},
                {'name': 'Adjectifs & Divers',
                 'words': [{'original': 'grand', 'translation': 'ookii'},
                           {'original': 'petit', 'translation': 'chiisai'},
                           {'original': 'lourd', 'translation': 'omoi'},
                           {'original': 'autre', 'translation': 'hoka no'},
                           {'original': 'different', 'translation': 'koto'},
                           {'original': 'comme', 'translation': 'sonna ni'},
                           {'original': 'comme ça', 'translation': 'sonna ni'},
                           {'original': 'ainsi', 'translation': 'soo'},
                           {'original': 'aussi', 'translation': 'mo'},
                           {'original': 'pour []', 'translation': '[] no tame'},
                           {'original': 'avec', 'translation': 'to'},
                           {'original': 'sans', 'translation': 'nashi'},
                           {'original': 'seul', 'translation': 'jibun'},
                           {'original': 'ensemble', 'translation': 'issho'},
                           {'original': 'couleur', 'translation': 'iro'},
                           {'original': 'bleu', 'translation': 'ao'},
                           {'original': 'rouge', 'translation': 'aka'},
                           {'original': 'vert', 'translation': 'midori'},
                           {'original': 'jaune', 'translation': 'ki iro'},
                           {'original': 'blanc', 'translation': 'shiro'},
                           {'original': 'noir', 'translation': 'kuro'},
                           {'original': 'combien', 'translation': 'ikutsu'},
                           {'original': '0', 'translation': 'zero'},
                           {'original': '1', 'translation': 'ichi'},
                           {'original': '2', 'translation': 'ni'}]},
                {'name': 'Chiffres & Quantité',
                 'words': [{'original': '3', 'translation': 'san'},
                           {'original': '4', 'translation': 'shi'},
                           {'original': '5', 'translation': 'go'},
                           {'original': '6', 'translation': 'roku'},
                           {'original': '7', 'translation': 'shichi'},
                           {'original': '8', 'translation': 'hachi'},
                           {'original': '9', 'translation': 'kyuu'},
                           {'original': '10', 'translation': 'juu'},
                           {'original': '11', 'translation': 'juu ichi'},
                           {'original': '12', 'translation': 'juu ni'},
                           {'original': '20', 'translation': 'ni juu'},
                           {'original': '100', 'translation': 'hyaku'},
                           {'original': '1000', 'translation': 'sen'},
                           {'original': '10000', 'translation': 'man'},
                           {'original': 'un peu', 'translation': 'chotto, shooshoo'},
                           {'original': 'moins', 'translation': 'miman'},
                           {'original': 'environ', 'translation': 'kurai'},
                           {'original': 'assez', 'translation': 'juubun'},
                           {'original': 'plus', 'translation': 'motto'},
                           {'original': 'plus que []', 'translation': '[] yori'},
                           {'original': 'le plus', 'translation': 'mottomo'},
                           {'original': 'beaucoup', 'translation': 'takusan'},
                           {'original': 'très', 'translation': 'totemo'},
                           {'original': 'trop', 'translation': 'amarinimo'},
                           {'original': 'oui', 'translation': 'hai'}]},
                {'name': 'Politesse',
                 'words': [{'original': 'non', 'translation': 'iie'},
                           {'original': 'bienvenue', 'translation': 'yoo koso (irasshaimashita)'},
                           {'original': 'bonjour', 'translation': 'konnichi wa'},
                           {'original': 'salut', 'translation': 'ohayoo gozaimasu'},
                           {'original': 'comment vas tu', 'translation': 'genki desu ka'},
                           {'original': 'merci, je vais bien',
                            'translation': 'okage samade, genki desu'},
                           {'original': 'comment vous appelez vous?',
                            'translation': 'o namae wa nan desu ka'},
                           {'original': "je m'appele []", 'translation': '[] desu'},
                           {'original': "d'où venez vous?", 'translation': 'dochira kara desu ka?'},
                           {'original': 'je suis de []', 'translation': '[] shusshin desu'},
                           {'original': 'enchanté', 'translation': 'hajimemashite'},
                           {'original': 'bonjour', 'translation': 'o hayoo gozaimasu'},
                           {'original': 'bonsoir', 'translation': 'konbanwa'},
                           {'original': 'bonne nuit', 'translation': 'oyasumi nasai'},
                           {'original': 'aurevoir', 'translation': 'sayoonara'},
                           {'original': 'je ne comprends pas', 'translation': 'wakarimasen'},
                           {'original': 'parlez plus lentement',
                            'translation': 'yukkuri hanashite kudasai'},
                           {'original': 'écrivez le', 'translation': 'kaite kudasai'},
                           {'original': "s'il vous plaît", 'translation': 'onegai shimasu'},
                           {'original': 'donnez moi []', 'translation': '[] o kudasai'},
                           {'original': 'merci', 'translation': 'arigatoo'},
                           {'original': 'je vous en prie', 'translation': 'doozo'},
                           {'original': 'excusez moi', 'translation': 'gomen nasai'},
                           {'original': 'pardon', 'translation': 'sumimasen'},
                           {'original': 'pas de problème', 'translation': 'daijoosu desu yo'}]},
                {'name': 'Divers',
                 'words': [{'original': 'voici', 'translation': 'doozo'},
                           {'original': 'bon appétit', 'translation': 'itadakimasu'},
                           {'original': 'santé!', 'translation': 'kanpai'},
                           {'original': "n'est ce pas", 'translation': 'ne'},
                           {'original': "ne t'inquiète pas", 'translation': 'shinpai shinaide'},
                           {'original': "je ne sais pas, je n'ai pas compris",
                            'translation': 'wakarimasen'}]}]}
