# Auto-generated from chat/vocabulary.py

LANGUAGE_DATA = {'display_name': 'Espagnol',
 'categories': [{'name': 'Alimentation',
                 'words': [{'original': 'nourriture', 'translation': 'comida'},
                           {'original': 'fruit', 'translation': 'fruta'},
                           {'original': 'légumes', 'translation': 'verduras'},
                           {'original': 'pain', 'translation': 'pan'},
                           {'original': 'fromage', 'translation': 'queso'},
                           {'original': 'viande', 'translation': 'carne'},
                           {'original': 'poisson', 'translation': 'pescado'},
                           {'original': 'sel', 'translation': 'sal'},
                           {'original': 'sucre', 'translation': 'azucar'},
                           {'original': 'eau', 'translation': 'agua'},
                           {'original': 'lait', 'translation': 'leche'},
                           {'original': 'café', 'translation': 'cafe'},
                           {'original': 'thé', 'translation': 'te'},
                           {'original': 'bière', 'translation': 'cerveza'},
                           {'original': 'vin', 'translation': 'vino'},
                           {'original': 'riz', 'translation': 'arroz'},
                           {'original': 'huile', 'translation': 'aceite'},
                           {'original': 'animal', 'translation': 'animal'}]},
                {'name': 'Expressions & Pensée',
                 'words': [{'original': 'quoi?', 'translation': 'que?'},
                           {'original': 'rien', 'translation': 'nada'},
                           {'original': 'quelque chose', 'translation': 'algo'},
                           {'original': 'tout', 'translation': 'todo'},
                           {'original': 'il y a', 'translation': 'hay'},
                           {'original': "il n'y a pas", 'translation': 'no hay'},
                           {'original': "c'est", 'translation': 'es'},
                           {'original': 'je veux', 'translation': 'quiero'},
                           {'original': "j'aime", 'translation': 'me gusta'},
                           {'original': 'je dois', 'translation': 'debo'},
                           {'original': 'je peux', 'translation': 'puedo'},
                           {'original': 'je pense', 'translation': 'pienso'},
                           {'original': 'peut-être', 'translation': 'quizas'},
                           {'original': 'et', 'translation': 'y'},
                           {'original': 'ou', 'translation': 'o'},
                           {'original': 'mais', 'translation': 'pero'},
                           {'original': 'parce que', 'translation': 'porque'},
                           {'original': 'pour', 'translation': 'para'},
                           {'original': 'aimer', 'translation': 'amar'},
                           {'original': 'pouvoir', 'translation': 'poder'},
                           {'original': 'pourquoi', 'translation': 'por que'}]},
                {'name': "Verbes d'action",
                 'words': [{'original': 'faire', 'translation': 'hacer'},
                           {'original': 'aller', 'translation': 'ir'},
                           {'original': 'venir', 'translation': 'venir'},
                           {'original': 'partir', 'translation': 'salir'},
                           {'original': 'attendre', 'translation': 'esperar'},
                           {'original': 'écrire', 'translation': 'escribir'},
                           {'original': 'lire', 'translation': 'leer'},
                           {'original': 'commencer', 'translation': 'empezar'},
                           {'original': 'finir', 'translation': 'terminar'},
                           {'original': 'entrer', 'translation': 'entrar'},
                           {'original': 'sortir', 'translation': 'salir'},
                           {'original': 'courir', 'translation': 'correr'},
                           {'original': 'voir', 'translation': 'ver'},
                           {'original': 'écouter', 'translation': 'escuchar'},
                           {'original': 'boire', 'translation': 'beber'},
                           {'original': 'manger', 'translation': 'comer'},
                           {'original': 'parler', 'translation': 'hablar'},
                           {'original': 'comprendre', 'translation': 'entender'}]},
                {'name': 'Pronoms & Lieux',
                 'words': [{'original': 'qui', 'translation': 'quien'},
                           {'original': 'moi', 'translation': 'yo'},
                           {'original': 'toi', 'translation': 'tu'},
                           {'original': 'il/elle', 'translation': 'el/ella'},
                           {'original': 'nous', 'translation': 'nosotros'},
                           {'original': 'vous', 'translation': 'vosotros/usted'},
                           {'original': 'ils', 'translation': 'ellos'},
                           {'original': 'ceci', 'translation': 'esto'},
                           {'original': 'cela', 'translation': 'eso'},
                           {'original': 'où', 'translation': 'donde'},
                           {'original': 'ici', 'translation': 'aqui'},
                           {'original': 'là', 'translation': 'alli'},
                           {'original': 'en haut', 'translation': 'arriba'},
                           {'original': 'devant', 'translation': 'delante'},
                           {'original': 'derrière', 'translation': 'detras'},
                           {'original': 'à gauche', 'translation': 'a la izquierda'},
                           {'original': 'à droite', 'translation': 'a la derecha'},
                           {'original': 'dans', 'translation': 'en'},
                           {'original': 'de', 'translation': 'de'}]},
                {'name': 'Maison & Ville',
                 'words': [{'original': 'maison', 'translation': 'casa'},
                           {'original': 'cuisine', 'translation': 'cocina'},
                           {'original': 'chambre', 'translation': 'habitacion'},
                           {'original': 'lit', 'translation': 'cama'},
                           {'original': 'salle de bain', 'translation': 'bano'},
                           {'original': 'table', 'translation': 'mesa'},
                           {'original': 'chaise', 'translation': 'silla'},
                           {'original': 'ville', 'translation': 'ciudad'},
                           {'original': 'rue', 'translation': 'calle'},
                           {'original': 'magasin', 'translation': 'tienda'},
                           {'original': 'arbre', 'translation': 'arbol'},
                           {'original': 'montagne', 'translation': 'montana'},
                           {'original': 'mer', 'translation': 'mar'},
                           {'original': 'soleil', 'translation': 'sol'},
                           {'original': 'voiture', 'translation': 'coche'},
                           {'original': 'bus', 'translation': 'autobus'},
                           {'original': 'train', 'translation': 'tren'},
                           {'original': 'voyage', 'translation': 'viaje'}]},
                {'name': 'Temps',
                 'words': [{'original': 'quand', 'translation': 'cuando'},
                           {'original': 'temps', 'translation': 'tiempo'},
                           {'original': 'jamais', 'translation': 'nunca'},
                           {'original': 'parfois', 'translation': 'a veces'},
                           {'original': 'souvent', 'translation': 'a menudo'},
                           {'original': 'toujours', 'translation': 'siempre'},
                           {'original': 'maintenant', 'translation': 'ahora'},
                           {'original': 'avant', 'translation': 'antes'},
                           {'original': 'après', 'translation': 'despues'},
                           {'original': 'matin', 'translation': 'manana'},
                           {'original': 'après-midi', 'translation': 'tarde'},
                           {'original': 'soir', 'translation': 'noche'},
                           {'original': 'nuit', 'translation': 'noche'},
                           {'original': "aujourd'hui", 'translation': 'hoy'},
                           {'original': 'demain', 'translation': 'manana'},
                           {'original': 'hier', 'translation': 'ayer'},
                           {'original': 'année', 'translation': 'ano'},
                           {'original': 'mois', 'translation': 'mes'}]},
                {'name': 'Adjectifs',
                 'words': [{'original': 'bon', 'translation': 'bueno'},
                           {'original': 'mauvais', 'translation': 'malo'},
                           {'original': 'beau', 'translation': 'bonito'},
                           {'original': 'grand', 'translation': 'grande'},
                           {'original': 'petit', 'translation': 'pequeno'},
                           {'original': 'chaud', 'translation': 'caliente'},
                           {'original': 'froid', 'translation': 'frio'},
                           {'original': 'vite', 'translation': 'rapido'},
                           {'original': 'lent', 'translation': 'lento'},
                           {'original': 'nouveau', 'translation': 'nuevo'},
                           {'original': 'ancien', 'translation': 'viejo'},
                           {'original': 'facile', 'translation': 'facil'},
                           {'original': 'difficile', 'translation': 'dificil'},
                           {'original': 'important', 'translation': 'importante'},
                           {'original': 'propre', 'translation': 'limpio'},
                           {'original': 'sale', 'translation': 'sucio'},
                           {'original': 'près', 'translation': 'cerca'},
                           {'original': 'loin', 'translation': 'lejos'}]},
                {'name': 'Chiffres & Quantité',
                 'words': [{'original': 'combien', 'translation': 'cuanto'},
                           {'original': 'un peu', 'translation': 'un poco'},
                           {'original': 'beaucoup', 'translation': 'mucho'},
                           {'original': 'moins', 'translation': 'menos'},
                           {'original': 'plus', 'translation': 'mas'},
                           {'original': 'très', 'translation': 'muy'},
                           {'original': 'trop', 'translation': 'demasiado'},
                           {'original': '0', 'translation': 'cero'},
                           {'original': '1', 'translation': 'uno'},
                           {'original': '2', 'translation': 'dos'},
                           {'original': '3', 'translation': 'tres'},
                           {'original': '4', 'translation': 'cuatro'},
                           {'original': '5', 'translation': 'cinco'},
                           {'original': '6', 'translation': 'seis'},
                           {'original': '7', 'translation': 'siete'},
                           {'original': '8', 'translation': 'ocho'},
                           {'original': '9', 'translation': 'nueve'},
                           {'original': '10', 'translation': 'diez'}]},
                {'name': 'Politesse',
                 'words': [{'original': 'oui', 'translation': 'si'},
                           {'original': 'non', 'translation': 'no'},
                           {'original': 'bonjour', 'translation': 'hola'},
                           {'original': 'salut', 'translation': 'hola'},
                           {'original': 'bonsoir', 'translation': 'buenas tardes'},
                           {'original': 'bonne nuit', 'translation': 'buenas noches'},
                           {'original': 'au revoir', 'translation': 'adios'},
                           {'original': "s'il vous plaît", 'translation': 'por favor'},
                           {'original': 'merci', 'translation': 'gracias'},
                           {'original': 'de rien', 'translation': 'de nada'},
                           {'original': 'excusez-moi', 'translation': 'disculpe'},
                           {'original': 'pardon', 'translation': 'perdon'},
                           {'original': 'comment ça va?', 'translation': 'como estas?'},
                           {'original': 'je vais bien', 'translation': 'estoy bien'},
                           {'original': 'je ne comprends pas', 'translation': 'no entiendo'},
                           {'original': 'parlez plus lentement',
                            'translation': 'hable mas despacio'},
                           {'original': 'comment vous appelez-vous?',
                            'translation': 'como se llama?'},
                           {'original': "je m'appelle []", 'translation': 'me llamo []'}]},
                {'name': 'Divers',
                 'words': [{'original': 'enfant', 'translation': 'nino/nina'},
                           {'original': 'garçon', 'translation': 'nino'},
                           {'original': 'fille', 'translation': 'nina'},
                           {'original': 'mère', 'translation': 'madre'},
                           {'original': 'père', 'translation': 'padre'},
                           {'original': 'frère', 'translation': 'hermano'},
                           {'original': 'soeur', 'translation': 'hermana'},
                           {'original': 'ami(e)', 'translation': 'amigo/a'},
                           {'original': 'mari', 'translation': 'marido'},
                           {'original': 'femme', 'translation': 'esposa'},
                           {'original': 'bon appétit', 'translation': 'buen provecho'},
                           {'original': 'santé!', 'translation': 'salud!'}]}]}
