# Auto-generated from chat/vocabulary.py

LANGUAGE_DATA = {'display_name': 'Turc',
 'categories': [{'name': 'Alimentation',
                 'words': [{'original': 'nourriture', 'translation': 'yiyecek'},
                           {'original': 'fruit', 'translation': 'meyve'},
                           {'original': 'légumes', 'translation': 'sebze'},
                           {'original': 'pain', 'translation': 'ekmek'},
                           {'original': 'fromage', 'translation': 'peynir'},
                           {'original': 'viande', 'translation': 'et'},
                           {'original': 'poisson', 'translation': 'balik'},
                           {'original': 'sel', 'translation': 'tuz'},
                           {'original': 'sucre', 'translation': 'seker'},
                           {'original': 'eau', 'translation': 'su'},
                           {'original': 'lait', 'translation': 'sut'},
                           {'original': 'café', 'translation': 'kahve'},
                           {'original': 'thé', 'translation': 'cay'},
                           {'original': 'bière', 'translation': 'bira'},
                           {'original': 'vin', 'translation': 'sarap'},
                           {'original': 'riz', 'translation': 'pirinc'},
                           {'original': 'huile', 'translation': 'yag'},
                           {'original': 'animal', 'translation': 'hayvan'}]},
                {'name': 'Expressions & Pensée',
                 'words': [{'original': 'quoi?', 'translation': 'ne?'},
                           {'original': 'rien', 'translation': 'hicbir sey'},
                           {'original': 'quelque chose', 'translation': 'bir sey'},
                           {'original': 'tout', 'translation': 'her sey'},
                           {'original': 'il y a', 'translation': 'var'},
                           {'original': "il n'y a pas", 'translation': 'yok'},
                           {'original': "c'est", 'translation': 'bu'},
                           {'original': 'je veux', 'translation': 'istiyorum'},
                           {'original': "j'aime", 'translation': 'seviyorum'},
                           {'original': 'je dois', 'translation': 'gerekiyor'},
                           {'original': 'je peux', 'translation': 'yapabilirim'},
                           {'original': 'je pense', 'translation': 'dusunuyorum'},
                           {'original': 'peut-être', 'translation': 'belki'},
                           {'original': 'et', 'translation': 've'},
                           {'original': 'ou', 'translation': 'veya'},
                           {'original': 'mais', 'translation': 'ama'},
                           {'original': 'parce que', 'translation': 'cunku'},
                           {'original': 'pour', 'translation': 'icin'},
                           {'original': 'aimer', 'translation': 'sevmek'},
                           {'original': 'pouvoir', 'translation': 'yapabilmek'},
                           {'original': 'pourquoi', 'translation': 'neden'}]},
                {'name': "Verbes d'action",
                 'words': [{'original': 'faire', 'translation': 'yapmak'},
                           {'original': 'aller', 'translation': 'gitmek'},
                           {'original': 'venir', 'translation': 'gelmek'},
                           {'original': 'partir', 'translation': 'ayrilmak'},
                           {'original': 'attendre', 'translation': 'beklemek'},
                           {'original': 'écrire', 'translation': 'yazmak'},
                           {'original': 'lire', 'translation': 'okumak'},
                           {'original': 'commencer', 'translation': 'baslamak'},
                           {'original': 'finir', 'translation': 'bitirmek'},
                           {'original': 'entrer', 'translation': 'girmek'},
                           {'original': 'sortir', 'translation': 'cikmak'},
                           {'original': 'courir', 'translation': 'kosmak'},
                           {'original': 'voir', 'translation': 'gormek'},
                           {'original': 'écouter', 'translation': 'dinlemek'},
                           {'original': 'boire', 'translation': 'icmek'},
                           {'original': 'manger', 'translation': 'yemek'},
                           {'original': 'parler', 'translation': 'konusmak'},
                           {'original': 'comprendre', 'translation': 'anlamak'}]},
                {'name': 'Pronoms & Lieux',
                 'words': [{'original': 'qui', 'translation': 'kim'},
                           {'original': 'moi', 'translation': 'ben'},
                           {'original': 'toi', 'translation': 'sen'},
                           {'original': 'il/elle', 'translation': 'o'},
                           {'original': 'nous', 'translation': 'biz'},
                           {'original': 'vous', 'translation': 'siz'},
                           {'original': 'ils', 'translation': 'onlar'},
                           {'original': 'ceci', 'translation': 'bu'},
                           {'original': 'cela', 'translation': 'su'},
                           {'original': 'où', 'translation': 'nerede'},
                           {'original': 'ici', 'translation': 'burada'},
                           {'original': 'là', 'translation': 'orada'},
                           {'original': 'en haut', 'translation': 'yukarida'},
                           {'original': 'devant', 'translation': 'onunde'},
                           {'original': 'derrière', 'translation': 'arkasinda'},
                           {'original': 'à gauche', 'translation': 'solda'},
                           {'original': 'à droite', 'translation': 'sagda'},
                           {'original': 'dans', 'translation': 'icinde'},
                           {'original': 'de', 'translation': '-den/-dan'}]},
                {'name': 'Maison & Ville',
                 'words': [{'original': 'maison', 'translation': 'ev'},
                           {'original': 'cuisine', 'translation': 'mutfak'},
                           {'original': 'chambre', 'translation': 'oda'},
                           {'original': 'lit', 'translation': 'yatak'},
                           {'original': 'salle de bain', 'translation': 'banyo'},
                           {'original': 'table', 'translation': 'masa'},
                           {'original': 'chaise', 'translation': 'sandalye'},
                           {'original': 'ville', 'translation': 'sehir'},
                           {'original': 'rue', 'translation': 'sokak'},
                           {'original': 'magasin', 'translation': 'magaza'},
                           {'original': 'arbre', 'translation': 'agac'},
                           {'original': 'montagne', 'translation': 'dag'},
                           {'original': 'mer', 'translation': 'deniz'},
                           {'original': 'soleil', 'translation': 'gunes'},
                           {'original': 'voiture', 'translation': 'araba'},
                           {'original': 'bus', 'translation': 'otobus'},
                           {'original': 'train', 'translation': 'tren'},
                           {'original': 'voyage', 'translation': 'seyahat'}]},
                {'name': 'Temps',
                 'words': [{'original': 'quand', 'translation': 'ne zaman'},
                           {'original': 'temps', 'translation': 'zaman'},
                           {'original': 'jamais', 'translation': 'asla'},
                           {'original': 'parfois', 'translation': 'bazen'},
                           {'original': 'souvent', 'translation': 'sik sik'},
                           {'original': 'toujours', 'translation': 'her zaman'},
                           {'original': 'maintenant', 'translation': 'simdi'},
                           {'original': 'avant', 'translation': 'once'},
                           {'original': 'après', 'translation': 'sonra'},
                           {'original': 'matin', 'translation': 'sabah'},
                           {'original': 'après-midi', 'translation': 'ogleden sonra'},
                           {'original': 'soir', 'translation': 'aksam'},
                           {'original': 'nuit', 'translation': 'gece'},
                           {'original': "aujourd'hui", 'translation': 'bugun'},
                           {'original': 'demain', 'translation': 'yarin'},
                           {'original': 'hier', 'translation': 'dun'},
                           {'original': 'année', 'translation': 'yil'},
                           {'original': 'mois', 'translation': 'ay'}]},
                {'name': 'Adjectifs',
                 'words': [{'original': 'bon', 'translation': 'iyi'},
                           {'original': 'mauvais', 'translation': 'kotu'},
                           {'original': 'beau', 'translation': 'guzel'},
                           {'original': 'grand', 'translation': 'buyuk'},
                           {'original': 'petit', 'translation': 'kucuk'},
                           {'original': 'chaud', 'translation': 'sicak'},
                           {'original': 'froid', 'translation': 'soguk'},
                           {'original': 'vite', 'translation': 'hizli'},
                           {'original': 'lent', 'translation': 'yavas'},
                           {'original': 'nouveau', 'translation': 'yeni'},
                           {'original': 'ancien', 'translation': 'eski'},
                           {'original': 'facile', 'translation': 'kolay'},
                           {'original': 'difficile', 'translation': 'zor'},
                           {'original': 'important', 'translation': 'onemli'},
                           {'original': 'propre', 'translation': 'temiz'},
                           {'original': 'sale', 'translation': 'kirli'},
                           {'original': 'près', 'translation': 'yakin'},
                           {'original': 'loin', 'translation': 'uzak'}]},
                {'name': 'Chiffres & Quantité',
                 'words': [{'original': 'combien', 'translation': 'ne kadar'},
                           {'original': 'un peu', 'translation': 'biraz'},
                           {'original': 'beaucoup', 'translation': 'cok'},
                           {'original': 'moins', 'translation': 'daha az'},
                           {'original': 'plus', 'translation': 'daha cok'},
                           {'original': 'très', 'translation': 'cok'},
                           {'original': 'trop', 'translation': 'fazla'},
                           {'original': '0', 'translation': 'sifir'},
                           {'original': '1', 'translation': 'bir'},
                           {'original': '2', 'translation': 'iki'},
                           {'original': '3', 'translation': 'uc'},
                           {'original': '4', 'translation': 'dort'},
                           {'original': '5', 'translation': 'bes'},
                           {'original': '6', 'translation': 'alti'},
                           {'original': '7', 'translation': 'yedi'},
                           {'original': '8', 'translation': 'sekiz'},
                           {'original': '9', 'translation': 'dokuz'},
                           {'original': '10', 'translation': 'on'}]},
                {'name': 'Politesse',
                 'words': [{'original': 'oui', 'translation': 'evet'},
                           {'original': 'non', 'translation': 'hayir'},
                           {'original': 'bonjour', 'translation': 'merhaba'},
                           {'original': 'salut', 'translation': 'selam'},
                           {'original': 'bonsoir', 'translation': 'iyi aksamlar'},
                           {'original': 'bonne nuit', 'translation': 'iyi geceler'},
                           {'original': 'au revoir', 'translation': 'hosca kal'},
                           {'original': "s'il vous plaît", 'translation': 'lutfen'},
                           {'original': 'merci', 'translation': 'tesekkur ederim'},
                           {'original': 'de rien', 'translation': 'rica ederim'},
                           {'original': 'excusez-moi', 'translation': 'affedersiniz'},
                           {'original': 'pardon', 'translation': 'ozur dilerim'},
                           {'original': 'comment ça va?', 'translation': 'nasilsin?'},
                           {'original': 'je vais bien', 'translation': 'iyiyim'},
                           {'original': 'je ne comprends pas', 'translation': 'anlamiyorum'},
                           {'original': 'parlez plus lentement',
                            'translation': 'daha yavas konusun'},
                           {'original': 'comment vous appelez-vous?', 'translation': 'adiniz ne?'},
                           {'original': "je m'appelle []", 'translation': 'benim adim []'}]},
                {'name': 'Divers',
                 'words': [{'original': 'enfant', 'translation': 'cocuk'},
                           {'original': 'garçon', 'translation': 'erkek cocuk'},
                           {'original': 'fille', 'translation': 'kiz cocuk'},
                           {'original': 'mère', 'translation': 'anne'},
                           {'original': 'père', 'translation': 'baba'},
                           {'original': 'frère', 'translation': 'erkek kardes'},
                           {'original': 'soeur', 'translation': 'kiz kardes'},
                           {'original': 'ami(e)', 'translation': 'arkadas'},
                           {'original': 'mari', 'translation': 'koca'},
                           {'original': 'femme', 'translation': 'es'},
                           {'original': 'bon appétit', 'translation': 'afiyet olsun'},
                           {'original': 'santé!', 'translation': 'serefe!'}]}]}
